### PR TITLE
Update Metatag to 1.16

### PR DESCRIPTION
**Pull request by Feng-Shui**
For issue #255 - updating Metatag to the 1.6 release specifically for the ability to verify site ownership for external services such as Google Webmaster tools, Bing etc.

Expecting the initial build and testing to fail...

### CODE REVIEW

**Comment by aleayr** [comment]
Hey @Feng-Shui, looks like you were expecting that outcome? Patch causing problems with the build?

**Comment by Feng-Shui** [comment]
Yep, just wanted to get a baseline.  I've got the current D.O patch re-rolled against 1.6 and am sorting out some failing tests (which I've just got all green on).  I'll post the patch back to D.O and then pull it into the make file and see if I can get a passing build.

**Comment by Feng-Shui** [comment]
@fiasco @jozhao (please tag anyone else you guys think should take a look at this one)

This PR updates Metatag from 1.4 to 1.16 not 1.6.  I've re-rolled the The D.O patch that we're currently running (mentioned in #255) against 1.16 and it's passing against the current dev branch: https://www.drupal.org/node/1970362

I'm hoping that now that it's passing the maintainer will be happy to reconsider committing it - I had to teak a number of the simple tests in Metatag and make a few other small changes to get it passing, but hopefully this can be kicked along again now.

I've had to update the behat tests for the new version, just small tweaks to fieldset labels and meta tag output.

Would appreciate some input here given this is a significant update. I'll read through the release notes between 1.4 and 1.16 today to see if anything looks concerning (initial skim yesterday looked ok).  Additionally, we may want to hold off on merging the PR in until the module maintainer is happy with the passing patch or until we've been able to confirm that the updated patch is still delivering the same functionality as the original patch against 1.4.

**Comment by fiasco** [comment]
Have RTBC'd the patch. WIll merge here.

**Pull request merged**
