### PR TITLE
Add OpenAccess module, external library and initial setup

### PR DESCRIPTION
**Pull request by yangli0516**
Added external PerformX library in the make file. The buttons from the plugin will be enabled during the setup.

### CODE REVIEW

**Comment by yangli0516** [comment]
The PerformX library hosted by CKEditor needs to be whitelisted. Working on the application.

**Comment by teamglenny** [comment]
Hi @yangli0516 do you want to start over on this one? Been some other progress in #48

**Comment by yangli0516** [comment]
Hi @teamglenny , sorry for the late reply. I've solved the branding issue in #48. Here I've updated govcms.install to download the latest version of the plugin.

**Comment by aleayr** [comment]
Do we need to rebase this, or should it merge successfully? @fiasco @invisigoth @jozhao

**Comment by aleayr** [comment]
I'm keen to get this over to @Venkata-modgu for testing

**Comment by fiasco** [comment]
has anything changed since Nov 30? if so we'll need to get test bot to rebuild the environment

**Comment by aleayr** [comment]
@yangli0516, are you able to pull in the latest changes from govCMS master and commit back to your repo to sync us up with a couple of changes that have happened since November?

Then we'll do final testing, and merge this in.

**Comment by yangli0516** [comment]
@aleayr, sure thing. I'll working on that.

**Comment by aleayr** [comment]
@jozhao What needs to be done on this one? Can you confirm?

**Comment by pandaskii** [comment]
@aleayr here is a checklist
- [x] anything changed since last pull request in Nov? Or we just needs a rebase
- [x] Supported versions of CKEditor - up to 4.5.\* @yangli0516 ? [Update CKEditor to  #4.5.7](164) Should we address this (Supported versions of CKEditor) somewhere such as requirements in module or disto profile?
- [x] Enable OpenAccess buttons in Rich Text profile - Should we enable it in govcms_editing custom/feature module instead of current way in disto installation file?
- [ ] Over to @Venkata-modgu for testing

**Comment by aleayr** [comment]
Been extensively testing this today, and it is fine to be merged in, with one change.

@yangli0516 Could I get the templates button to be disabled by default until we can work out a way for agencies to easily add new templates to the list (I couldn't work it out)?

Once that setting for the template button has been removed, I'll retest and merge in.

**Comment by yangli0516** [comment]
@aleayr Thanks for the feedback. I'll let you know when it's done.

**Comment by aleayr** [comment]
Thanks @yangli0516 There is an imminent release (next few days) that I'd love to get this into :)

**Comment by yangli0516** [comment]
Hi @aleayr The commit has been amended that the template button is excluded by default. Please review.

**Comment by aleayr** [comment]
And this one is completed :) Thanks @yangli0516

**Pull request merged**
