### PR TITLE
Update navbar to 7.x-1.7 (from 7.x-1.6)

### PR DESCRIPTION
**Pull request by deanvucic**
## https://www.drupal.org/project/navbar/releases/7.x-1.7

Release notes
Issue #2550367 by eshta: Use full window location for back to site length.
Issue #2571289 by eshta, hass: Rename 'Menu' to 'Manage' to better align with Drupal 8
Issue #2434655 by eshta, partdigital: Update menu tree build process to review access for each load
Issue #2509740 by eamonogealagain: Fix Modernizr version detection regex.
Issue #2477473 by eshta: In narrowest viewports, make the vertical toolbar menu 100% width
Issue #2448023 by eshta: Remove unused CSS.
Issue #2182939 by eshta: Add modernizr.min.js as an accepted minified filename.
Issue #2429669 by eshta: Fix body 'shake' on table pages by caching the top displacement amount.
Issue #2448925 by msound: Fix line ending in navbar.make.example.
Issue #2227293 by hass, lsolesen: Remove navbar from print view.

### CODE REVIEW

**Review by pandaskii — APPROVED** [review]
Ready for testing

**Comment by pandaskii** [comment]
For testing, please hold until following two PRs are approved

- https://github.com/govCMS/govCMS/pull/588

- https://github.com/govCMS/govCMS/issues/585

@Venkata-modgu @deanvucic

**Comment by invisigoth** [comment]
@Venkata-modgu this needs to be tested in conjunction with the library updates as mentioned by @pandaskii above. Please be sure you update both this module and the libraries.

**Comment by Venkata-modgu** [comment]
Navbar tested in conjunction with the Backbone, Underscore and Modernizr library updates. 
Navigation bar working fine. 
Test passed.

**Pull request merged**
