### PR TITLE
[GOVCMSD7-154] Update xmlsitemap 7.x-2.6 (from 7.x-2.5) 

### PR DESCRIPTION
**Pull request by suhyeonh**
### https://www.drupal.org/project/xmlsitemap/releases/7.x-2.6
Release notes
Add a summary here

Contributors (34)
Dave Reid, VicOnt, saurabh-chugh, RenatoG, darrell_ulm, klausi, pifagor, cilefen, hockey2112, drupal-son, joshua.boltz, virtualbrian, jerry, milodesc, shi99, pfrenssen, Vj, japo32, voleger, alex_optim, efruin, toomanypets, ac, dgtlmoon, Chris Burge, PascalAnimateur, jenlampton, ecvandenberg, philsward, quicksketch, jmdorian, interdruper, millerrs, gaurav.bajpai

Changelog
Issues: 8 issues resolved.

Changes since 7.x-2.5:

Bug
#3003888 by VicOnt, saurabh-chugh, RenatoG: 'No description available' appears modules list
#3002557 by Dave Reid: Fix coding standards in xmlsitemap.api.php
#2986847 by darrell_ulm, klausi, pifagor, cilefen, hockey2112, drupal-son, joshua.boltz, virtualbrian, jerry, milodesc, shi99, pfrenssen, saurabh-chugh, Vj, japo32, voleger, alex_optim, efruin: TypeError: Argument 1 passed to xmlsitemap_node_create_link() must be an instance of stdClass, boolean given
#2996092 by toomanypets, pifagor, ac, dgtlmoon, alex_optim: Use of undefined constant XMLSITEMAP_BATCH_LIMIT
#2244449 by Chris Burge, Dave Reid, pifagor, PascalAnimateur, jenlampton, ecvandenberg, philsward, quicksketch, jmdorian, interdruper, millerrs, gaurav.bajpai: Use Protocol-less URL for XSL File
Task
#2997969 by pifagor, voleger: Delete a code that is not in use
#2997967 by pifagor, voleger: Delete a code that is not in use xmlsitemap.generate.inc

### CODE REVIEW

**Comment by tobybellwood** [comment]
fixes #860

**Review by ruwanl — APPROVED** [review]

**Comment by tobybellwood** [comment]
Fixes PHP7.2 compatibility issue https://www.drupal.org/project/xmlsitemap/issues/2996092

**Comment by fubarhouse** [comment]
This is now the only issue holding up the release of compatibility for PHP 7.2.

**Comment by brett-sargeant** [comment]
Is this one likely to end up in a release at some point?

**Review by sonnykt — APPROVED** [review]

**Comment by seanhamlin** [comment]
+1 for this to be merged. It is actively causing cron to fail on multiple production sites.

**Pull request merged**
