### PR TITLE
SA-CONTRIB-2018-053 Upgrade xmlsitemap to 7.x-2.x-dev (from 7.x-2.3)

### PR DESCRIPTION
**Pull request by tobybellwood**
## https://www.drupal.org/sa-contrib-2018-053
Project: XML sitemap
Date: 2018-July-18
Security risk: Moderately critical 13∕25 AC:None/A:None/CI:Some/II:None/E:Theoretical/TD:Uncommon
Vulnerability: Information Disclosure
Description: This module enables you to generate XML sitemaps and it helps search engines to more intelligently crawl a website and keep their results up to date.

The module doesn't sufficiently handle access rights under the scenario of updating contents from cron execution.

Solution: If you use the XML sitemap module for Drupal 7.x, upgrade to XML sitemap 7.x-2.4

## https://www.drupal.org/project/xmlsitemap/releases/7.x-2.4
Release notes
Changes since 7.x-2.3:

Excluding unpublished nodes from XML sitemap.

### CODE REVIEW

**Comment by tobybellwood** [comment]
Test this

**Review by pandaskii — DISMISSED** [review]
This tag is not merged with 7.x-2.x branch by the maintainer yet. Considering it is a  security release and codes review is passed, happy to merge it after the testing. 

Testing steps:

1. Disable this module at first
2. Adding testing nodes (published and unpublished nodes)
3. Enable this module and run the cronjob manually (Update the status of the testing nodes before and during the cronjob for example from published to draft)
4. Check generated sitemap.xml

**Review by pandaskii — CHANGES_REQUESTED** [review]
Found a bug and patch has been submitted to Drupal.org https://www.drupal.org/project/xmlsitemap/issues/2983150#comment-12698673

**Comment by tobybellwood** [comment]
Drupal.org patch has seemingly been superceded by https://www.drupal.org/project/xmlsitemap/issues/2986847

**Comment by tobybellwood** [comment]
Additional patch identified at https://www.drupal.org/project/xmlsitemap/issues/2987125

Not releasing to GovCMS whilst there are unresolved breaking issues - will keep a close eye on these patches.

**Review by pandaskii — APPROVED** [review]
With all the necessary fixes to the bugs from last security release, happy to merge it since the next module release may take a while

**Pull request merged**
