### PR TITLE
Accessible slider controls

### PR DESCRIPTION
**Pull request by alex-page**
Added slide title and number to the slide pagination controls. This is related to the issue #264

### CODE REVIEW

**Comment by deanvucic** [comment]
This will be considered for future milestones. For now, I'm closing this PR.

**Comment by alex-page** [comment]
@deanvucic @tobybellwood Do you have a location I can view future milestones? 

As a contributor it's disheartening to get this comment 1 year later. Comments like this I feel do not impact positively towards the community who are trying to make this a better product.

Surely a small PR that fixes an accessibility issue on every website using GovCMS and a Slider/Carousel can be implemented without too much hassle.

**Comment by Feng-Shui** [comment]
@alex-page there's been a massive amount of activity on the issue queues in the last 48 hours, it seems to me that a major review of outstanding issues is going on.  I also suspect that development is about to shift to the D8 version and so things like this will prob need to get prioritised along with the rest of the outstanding quests/issues for the D7 branch.  Could be wrong, just a guess.

On your point that this response is disheartening, I wouldn't take it that way.  I've got some open from July 2016 that had a week or two's worth of work on them, it's still valuable to have them there.  I'm sure you guys know how difficult it can be wrangle incoming PRs with limited resources etc, one of our guys asked about putting a PR up for the Kit last week but was told to hold off for now.  It's not that it wasn't welcome, it's just that things can move slowly at times.

Keep the PRs coming if you notice issues, we pick things up from PRs from time to time even if they take a long time to make it into a release.  IMO, every contribution to the project is welcome :)

**Comment by tobybellwood** [comment]
Hey @alex-page and @Feng-Shui - thanks for chasing.  We're doing a huge cleanup atm, and yes some things are being de-prioritised in favour of long term stability at d7, and pushing d8 forwards.

We're also unable to restart our Jenkins builds and test harnesses for any builds older than 6 months, so we'll have to grab this one out and resubmit.  We're trying to address the module upgrade and patch backlog as a priority, but we'll add this to the list for the next release given the re-interest.

You'll notice that we're currently doing intense bursts of PR activity, which isn't ideal, and things that aren't top of mind do get missed (especially with a backlog the size of ours).  We do rely on interest, and we really genuinely want to be responsive, but as you point out, it is really hard, and things do move slowly!

If you ever want a catch up on where we're at, drop me a line, and if you've got advice on where to prioritise our effort, let us know.

**Comment by tobybellwood** [comment]
As for viewing milestones - we're doing this at https://github.com/govCMS/govCMS/milestones?direction=asc&sort=due_date&state=open

We've also got a current sprint project at https://github.com/govCMS/govCMS/projects/4 where we're tracking current progress.

The main issue for our module backlog is at https://github.com/govCMS/govCMS/issues/529

**Comment by alex-page** [comment]
Thanks for all the information @tobybellwood that's really awesome 👍

Totally agree @Feng-Shui, my comment was more related to the lack of information. Which has now been addressed 😄

**Pull request closed without merging**
