### PR TITLE
Update minisite 7.x-1.0-alpha2

### PR DESCRIPTION
**Pull request by pandaskii**
Fix a minisite path issue.

### CODE REVIEW

**Comment by aleayr** [comment]
Venkata, can you please test this?

**Comment by Venkata-modgu** [comment]
Minisite updated to 7.x-1.0-alpha2.

**Comment by Venkata-modgu** [comment]
Minisite URL alias is not working.

**Comment by Venkata-modgu** [comment]
Test passed.
Minisite URL alias is working fine.

**Review by aleayr — APPROVED** [review]
Venkata confirms testing passed.

**Pull request merged**
