### PR TITLE
Roll patch for LinkIt/Paragraphs incompatibility issue

### LINKED ISSUE #63: LinkIt and Paragraphs compatibility issue
As mentioned in #62, LinkIt is [currently incompatible](https://www.drupal.org/node/2550845#comment-10351297) with editing Paragraphs that have been loaded via ajax.

To reproduce this:
1. Ensure you have a Paragraphs bundle with a field that has a WYSIWYG attached to it
2. Ensure you have a content type with a paragraphs item field with the default edit mode set to "closed" or "preview"
3. Create a new node and add at least one paragraphs item with a wysiwyg
4. Save the node
5. Edit the node, Click "Edit" on the paragraph, Click the LinkIt button

I have submitted a [patch](https://www.drupal.org/node/2550845#comment-10355269) to LinkIt but it has not yet had any response. It is possible to workaround this issue using `hook_element_info_alter()`. 

I will submit two pull requests, one working around the issue in the govcms_editing feature module, and the other applying the patch to LinkIt.

### PR DESCRIPTION
**Pull request by mstrelan**
Fixes #63

### CODE REVIEW

**Comment by fiasco** [comment]
Out of curiosity, how far away is this patch from being committed to the LinkIt module?

**Comment by mstrelan** [comment]
I posted the patch over two weeks ago but it has had no response yet. https://www.drupal.org/node/2550845#comment-10355269

**Comment by teamglenny** [comment]
Any progress, @mstrelan ?

**Comment by mstrelan** [comment]
@teamglenny this pull request provides a workaround for the issue. #65 provides a patch for LinkIt to fix the issue. Considering I have had no response from the LinkIt maintainer it is over to the GovCMS team to determine if they want to include either #64 or #65.

**Comment by invisigoth** [comment]
Issue #63 has been updated with an alternative solution without applying a patch. Please test and comment.

**Comment by mstrelan** [comment]
Closing in favour of #161

**Pull request closed without merging**
