### PR TITLE
Update honeypot to 7.x-1.22 (from 7.x-1.17)

### PR DESCRIPTION
**Pull request by tobybellwood**
## https://www.drupal.org/project/honeypot/releases/7.x-1.22

Release notes
New features / major changes:
- #2674008: Remove usage of Flood service from Honeypot
- #2674952: Switch to REQUEST_TIME instead of time() in honeypot_cron and honeypot_get_time_limit
- #2562733: Only allow [A-Za-z] first character for Honeypot class name
- #2608060: Rebuild CSS when the element name changes due to changing variable
- #2677126: Honeypot should not be triggered on programmatically submitted forms.

Bug fixes:
- #2663734: Fix doxygen comments for some hooks

## https://www.drupal.org/project/honeypot/releases/7.x-1.21

Release notes
Bug fixes:
- #2553319: disable page cache through the API rather than hacking global conf
- #2541026: Fix notice in honeypot_get_time_from_signed_timestamp()
Please make sure you run database updates if updating from 7.x-1.18 or earlier, and if you have trouble with the honeypot field showing up on your forms, you can also try going to the Honeypot admin page and re-saving your configuration.

Also, note that the 7.x-1.20 release was accidentally tagged from the Drupal 8 branch of the Honeypot module, so you should not attempt to update to 7.x-1.20.

## https://www.drupal.org/project/honeypot/releases/7.x-1.20

Please do NOT update to this release—this tag was accidentally created from the 8.x branch of the Honeypot module and will bring down your site if you update to it.
Instead, please update to the 7.x-1.21 release.

## https://www.drupal.org/project/honeypot/releases/7.x-1.19

Release notes
After Honeypot 7.x-1.18, some sites had issues with running module updates and/or generating Honeypot's CSS files. This release should fix both issues (as well as a few other small bugs), and also introduces a couple new features. Special thanks to everyone who submitted patches and issues that were added to this release!

New features:
- #2525760: Sign timestamp values
- #2324223: Warn user if certain common field names are used as Honeypot element name

Bugs fixed:
- #2508353: Remove .gitignore
- #2509442: Honeypot 7004 fails if module disabled
- #2491723: Check honeypot_expire when counting honeypot_users
- #2503309: Honeypot does not ensure that honeypot.css exists or is consistent with variable 'honeypot_element_name'

This release is in feature-parity with the corresponding Drupal 8.x-1.x releases.

## https://www.drupal.org/project/honeypot/releases/7.x-1.18

Release notes
A number of small bug fixes and a couple tiny new features—the focus in this release is on stability and fixing small bugs when integrating Honeypot with various contrib module forms. This release keeps the 7.x branch in feature parity with the new 8.x branch.

Bugs fixed and new features in this release:
- #1355374: Hide blank field when form displayed in modal
- #2394987: XHTML validation fails due to autocomplete="off" attribute
- #2480185: honeypot_get_protected_forms cache not working properly
- #2504015: Don't show help text on module install in CLI contexts

### CODE REVIEW

**Comment by tobybellwood** [comment]
Test this

**Review by pandaskii — APPROVED** [review]
Ready for testing

**Comment by Venkata-modgu** [comment]
Unable to access PR environment.

**Comment by tobybellwood** [comment]
Test this

**Comment by tobybellwood** [comment]
Closing to resubmit for testing as #623.

**Pull request closed without merging**
