### PR TITLE
Update Modernizr to 3.5.0 (from 2.7.0)

### PR DESCRIPTION
**Pull request by deanvucic**
## Release notes (v2.8)
https://github.com/Modernizr/Modernizr/releases/tag/v2.8.0

- Fix ie 10 form-validation detection
- Fix crash with Modernizr crashing firefox when used in a hidden iframe 
- Fix notification api test 
- Improve websocket detect 
- Update blob constructor test due to deprecation in Firefox 
- Add css-shapes detect 

## Release notes (v2.8.1)
https://github.com/Modernizr/Modernizr/releases/tag/v2.8.1

- fix css-shapes test

## Release notes (v2.8.2)
https://github.com/Modernizr/Modernizr/releases/tag/v2.8.2

- formvalidation was not backported correctly.

## Release notes (v2.8.3)
https://github.com/Modernizr/Modernizr/releases/tag/v2.8.3

- fix backporting of workers-blobworkers detect

## Release notes (v3.0)
https://modernizr.com/news/modernizr-3-new-release-site

- No detect names are hyphenated anymore; e.g. battery-api → batteryapi, flexbox-legacy → flexboxlegacy, etc 
- Modernizr.contentsecuritypolicy has been removed, as the JS API it was testing is deprecated 
- Modernizr.touch has been removed in favor of touchevents and pointerevents 
- Modernizr.pointerevents now detects DOM PointerEvent support, rather than CSS pointer-events 
- Detect for CSS pointer-events is now called csspointerevents
- Fixed false-positives in fontface detect 
- Our tests for Flexbox have been revised to better match developers’ expectations:
- Modernizr.flexbox returns true if flex-basis is supported – which represents a “reasonable” modern spec implementation (Chrome, FF, Safari and IE11 all pass this)
- Modernizr.flexwrap has been added to detect features missing from Firefox’s implementation
- Modernizr.flexboxtweener has been added to detect the implementation used by IE10
- Modernizr.flexboxlegacy remains unchanged
- WebGL detect is now more reliable, using HTMLCanvasElement.supportsContext() where available 
- WebGL extension enumerations are now attached to Modernizr.webglextensions rather than Modernizr.webgl
- The datauri detect now has a over32kb subproperty which will be true if the browser supports data URIs longer than 32 kB
- audio detect now also checks support for the Ogg Opus codec, exposed as Modernizr.audio.opus
- audiodata detect has been removed, because the implementation was very poor; this spec has been deprecated in favor of the Web Audio API
- video detect now has an hls subproperty representing support for the HLS video format
- todataurljpeg, todataurlpng and todataurlwebp are no longer asynchronous
- fullscreen detect has been updated to use document.exitFullScreen rather than the prefixed versions of document.cancelFullScreen as per the latest spec
- indexeddb detect now has a deletedatabase subproperty, representing support for the indexedDB.deleteDatabase() method which isn’t implemented in some browsers 
- webp detect now has lossy, lossless and alpha subproperties, representing support for various variants of the WebP format; the root webp property still represents basic lossy support
- Fixed a bug in cssvwunit, cssvminunit and cssvmaxunit which could give incorrect results when scrollbars are present 
- Fixed a bug in emoji detect where the test could stop working once minified
- Fixed a bug in regions detect where wrong result could be given when page is zoomed
- Fixed a bug in csstransforms3d detect where wrong result could be given when page is zoomed 
- Fixed a false-positive for the cssscrollbar detect in IE9
- Fixed a bug where indexeddb would throw an error if indexedDB was disabled via a browser flag 
- Fixed various false-positives in fileinput detect
- Fixed various incorrect results in history detect 
- Fixed a false-positive for cookies detect in IE9 
- Fixed a false-negative for csstransforms3d in WebKit browsers when certain styles are present on the page
- Fixed a bug where a page reload could crash Safari 5.1
- Fixed cssmask detect (a typo meant it was ineffective)
- Fixed userselect detect (a typo meant it was ineffective)
- Fixed a bug in displaytable detect when page is in RTL 
- Improved accuracy of xhr2 detect in Firefox 3.6
- Improved accuracy of customprotocolhandler detect in Android 2.x 
- Blacklisted Android 1.x & 2.x from passing the csstransforms detect, because it’s excessively buggy (#903)
- Fixed backgroundblendmode detect

APIs
- Modernizr used to include a Function.prototype.bind polyfill (this was documented, but was somewhat hidden); this has been removed
- testProp(), testAllProps() and prefixed() now use CSS.supports() under the hood for most CSS feature detects where available, improving performance and accuracy
- Modernizr.load has been deprecated in favor of using yepnope.js directly; from v3.0, yepnope.js must be included in the page in order for Modernizr.load to work: calling .load() will simply pass the arguments on to yepnope(); this will be removed fully in a future release 
- New Modernizr.on() API, for handling asynchronous detects
- New prefixedCSS() API, which functions like prefixed() but returns the prefixed property name in kebab-case (hyphenated, as used in CSS) instead of camelCase 
- testProp(), testAllProps(), prefixed() and prefixedCSS() now accept property names in either camelCase or kebab-case; for prefixed*() the format of the response depends on which function you call: prefixed() always returns camelCase, prefixedCSS() always returns kebab-case) 
- New noPrefixes build option, which forces feature detects to only return true if the feature is supported without a vendor prefix
- New enableJSClass build option, which determines whether or not to add js/no-js classes to the <html> element when Modernizr runs; true by default
- hasEvent() previously used “appropriate” elements for certain tests: submit would be tested against a <form> element, error would be tested against an  element, etc; this is no longer the case – for consistency, all will be tested against a <div>, unless otherwise specified by the optional elem argument 
hasEvent()'s optional elem argument can now be an element or simply a tag name, e.g. Modernizr.hasEvent('click', 'a')
- If a classPrefix is specified as a build option, it will be applied to no-js/js classes as well (previously this only applied to feature classes)
- Fixed a bug where classPrefix wasn’t applied to the class set for the first-executed feature detect 
testProp() and testAllProps() now accept up to 3 arguments: testProp(prop, [value, [skipValueTest]]); if a value is provided, Modernizr will ensure that value is supported for the named CSS property, delegating to CSS.supports() where available; if skipValueTest is true (default is false), the value test won’t be conducted when CSS.supports() isn’t available
- addTest() will now set subproperties if given a property name containing a period (.), which can be used for defining custom structured detects, or for extending existing detects (e.g. adding custom codec detects to Modernizr.audio)
- Fixed a bug where calling Modernizr.prefixed() with an obj argument which doesn’t support binding would throw an exception 
- Fixed a bug where calling Modernizr.mq() inside a hidden iframe would throw an error in Firefox 

## Release notes (v3.1.0)
https://modernizr.com/news/modernizr-3-1-0

Fixed
fixed the casing on the Flash documentation
fixed an incorrect URL for the cupcakejs sessionStorage polyfill 
fixed the crud out of the Modernizr SVG logo 
removed an unused dependency from the fullscreen detect 
fixed inaccurate false negatives in the vunit detect on iOS 8+ - 
fixed a request loop on the form validation detect with Opera Mini servers 

Updated

updated the npm build script to use his updated version of travis-scripts 
updated the Travis build image
updated the metadata for jQuery-contextMenu
embeded website info for the contributors to the project in the package.json 
updated the README's build instruction
updated html5shiv to v3.7.2, fixed an existing issue Modernizr and Browserify

Added
submitted a detect for backdrop-filter, with an assist from @KuraFire
added a lowercased version of the version flag (-v)
added the prefixedCSSValue utility function, as a way to check for prefixed versions of CSS values 
added Microsoft Edge to the saucelabs configuration
added a detect for jpeg2000 
added to the project, an awesome service that automatically pins your dependencies and PRs any updated in the future. Included in its updates since the last release are
updating proxyquire to v1.7.3 from v1.7.2
updating joi to v6.9.0 from v6.7.1
updating yargs to v3.26.0 from 2.3.0
updating grunt-contrib-jade to v0.15.0 from v0.14.1

## Release notes (v3.2.0)
https://modernizr.com/news/modernizr-3-2-0

fixed the unprefixed gradient detect to cover newer gradient syntaxes
fixed a long standing issue with the css hyphens detect
fixed the audio preload detect to be a functional check rather than simply a property check
fixed a (rather than) edge case in the transform3d detect
fixed a typo
added a hasOwnProperty check to the Modernizr class name creation process to avoid extraneous classes
fixed the sizes detect (used in responsive images) for Safari 9 
Added

added a detect for XDomainRequest
added a basic detect for the new Crypto APIs
created a detect for the Base64 API
created a detect for the BDI element
added a config to force LF line endings
added a basic detect for the new Crypto APIs
Updated

@paulirish updated the docs to the hiddenscroll detect
Updated Dependencies

updating yargs to v3.26.0 to v3.28.0
updating joi to v6.9.0 to v6.9.1
updating load-grunt-tasks to v0.2.1 to v3.3.0
updating grunt-contrib-copy to v0.8.1 to v0.8.2
updating grunt-contrib-clean to v0.4.1 to v0.6.0
updating marked to v0.2.10 to v3.5.0, which actually fixes several code vulnerabilities

## Release notes (v3.3.0)
https://modernizr.com/news/modernizr-3-3-0

Fixed

fixed the mp3 audio detect for Firefox by adding the proper codec
fixed an issue where the flash detect could add a fake body when it didn't need too, which screwed up IE 8 (R.I.P.)
fixed the dependency ordering for requirejs on the css filters detects (whoops!) 
fixed a false negative issue in nth test 
fixed an issue where setClasses was not being included despite being added via config
fixed a handful of errors that cropped up in older browsers in 078aea
fixed a regression in the input type=number detect in 695fd5
fixed base64 video used in the video autoplay detect, which was causing false negatives in some browsers
fixed an issue where custom tests weren't allowed to be passed into the buildQuery function
fixed a typo in the xdomainrequest detect
fixed false positive in Notifications test for Chrome on Android
fixed the syntax for form validation to allow it to run in XHTML mode
Added

added that Modernizr follows the Open Code of Conduct
added a detect for Safari's new Force Touch/3D Touch API
added a detect for CSS hairlines
added a detect for ES6 collections
added a detect for font ligatures
added a detect for crossOrigin support on the img tag
added a detect for jpeg 2000
added a detect for css snap scroll points
Updated

updated the base64 detect property to not use a hyphen by default (but still register one via an alias)
updated a bunch of style fixes as the result of a new jscs version
simplified the bdi check in 8d5169
Updated Dependencies

updated joi from v6.9.1 to v6.10.0
updated grunt-contrib-clean from v0.6.0 to v0.7.0
updated doctrine from v0.6.4 to v1.1.0
updated yargs from v3.29.0 to v3.31.0
updated requirejs from v2.1.20 to v2.1.22
updated grunt-contrib-connect from v0.5.0 to v0.11.2
added serve-static to compensate for changes in newer versions of grunt-contrib-connect
updated grunt-contrib-jscs from v1.8.0 to v2.6.0
updated grunt-contrib-mocha from v0.4.13 to v0.4.15
updated grunt-saucelabs from v8.6.1 to v8.6.2
updated load-grunt-tasks from v3.3.0 to v3.4.0

## Release notes (v3.3.1)
https://modernizr.com/news/modernizr-3-3-1

Fixed

fixed an issue where the indexeddb check threw an error when cookies are blocked in Firefox
fixed an issue where multiple build() calls in quick succession caused contaminated build
fixed a typo preventing an indexedDB subtest from ever runnning
fixed an where the cli version of modernizr would crash when using the inline feature-detect flags
updated a bunch of documentation links to https
Updated Dependencies
updated jquery from v1.11.3 to v1.12.0
updated lodash from v3.10.1 to v4.0.0, including some compat fixes

## Release notes (v3.4.0)
https://modernizr.com/news/modernizr-3-4-0

Fixed

fixed the opus audio detect to be more reliable on certain mobile devices
fixed the unicode test to not throw an err in XHTML pages
fixed the vml detect to not throw an err in XHTML5 pages
fixed himself from commiting build files yet again
fixed a glaring typo in the docs
fixed the prefixing helper
fixed the preserve-3d detect for IE 11 and Windows 10
fixed the history detect for file:// pages
fixed the generatedcontent detect for zoomed pages
fixed the video autoplay detect from crashing in certain situations
fixed the css regions detect
fixed a whole mess of doc typos
fixed the datachannel detect to work correctly in Edge 15

Updated

updated the build URL to use https instead of http for links
updated the IndexedDB detect to be more fine grained with feature detection
added the alias svgincss for svgasimg
inverted the internal logic of the transformstylepreserve3d detect to make it more readable
updated a few tests to not use the Boolean constructor
removed some duplicat entries from the config-all file
updated support detect metadata to have a valid url
updated the localizednumber test 
updated the fontface detect to remove old android due to very low usage
updated the indexeddbblob detect to ensure the puts are successful
updated the es6 string detect to check for includes instead of contains 

Added

created a detect for es6 arrow functions
created a detect for RTC Message Channels
created a detect for hover and pointer media queries
added the ability to use setClasses via a flag on the cli 
added a detect for CSS Transforms Level 2
added a detect for custom elements

Updated Dependencies

updated yargs from v3.30.0 to v6.6.0
updated lodash from v3.10.1 to v4.17.4
removed grunt-jscs 
removed grunt-contrib-jshint
updated grunt-istanbul from v0.4.2 to v0.7.1
updated grunt-saucelabs from v8.6.1 to v9.0.0
removed marked
added remarkable
added eslint 
removed support for Node 0.10 (only affects the cli tool)
updated proxyquire from v1.7.3 to v1.7.11

## Release notes (v3.5.0)
https://modernizr.com/news/modernizr-3-5-0

Instead of quietly updating the library like we did for our 3.4.0 release (yes, that happened — see the full changelog here), we have an exciting new feature detect as part of 3.5.0: CSS Grids!

With browsers adding support for CSS Grids in their latest releases, the time to start using CSS Grids is truly here. Just one caveat: IE11 and current shipping versions of Edge do not support the new syntax, but do support the old legacy CSS Grids proposal—and only one of them supports, uh, @supports.

So in 3.5.0 we’re adding two tests in one: the now-standard official CSS Grid syntax as Modernizr.cssgrid, and the old proposal’s syntax as Modernizr.cssgridlegacy. There is also an additional polyfill available for the Pointer Events test, named PEP. Lastly, dependencies were updated.

Happy developing!

New Feature Detect(s)

added CSS Grid test for old & new syntaxes
added PEP to pointer events as a polyfill
Updated Dependencies
Update grunt-contrib-clean to version 1.1.0
Update yargs to version 7.0.2

### CODE REVIEW

**Comment by fiasco** [comment]
I'm pretty hesitant to support this change purely because we don't know what the impact would be to upgrade Modernizer by a major version. This would likely break other sites.

**Comment by patrickkettner** [comment]
@fiasco the breaking changes are actually fairly small. It's big changes were in its internal tooling. The most commonly hit change would probably be `Modernizr.touch` changing to `Modernizr.touchevents`. I'd be happy to help y'all if I can in any way

**Comment by Rowno** [comment]
Just FYI, you've unintentionally notified every single person mentioned in the Modernizr changelog.

**Comment by tobybellwood** [comment]
We'll aim small and look at the 2.8.3 release in #585 - closing this PR

**Pull request closed without merging**
