### PR TITLE
Update HTML5Placeholder to 2.3.1 (from 2.0.8)

### PR DESCRIPTION
**Pull request by deanvucic**
## Release notes (v2.0.9)
https://github.com/mathiasbynens/jquery-placeholder/releases/tag/v2.0.9

- Fixed potential problem caused when other js libraries inject DOM elements right after input/textareas with placeholders
- Adds AMD support

## Release notes (v2.1.0)
https://github.com/mathiasbynens/jquery-placeholder/releases/tag/v2.1.0

- Now it's possible use a custom css class instead of the default .placeholder. See docs for examples. #38
- Minified version now available

## Release notes (v2.1.1)
https://github.com/mathiasbynens/jquery-placeholder/releases/tag/v2.1.1

- Removed bower dependency

## Release notes (v2.1.2)
https://github.com/mathiasbynens/jquery-placeholder/releases/tag/v2.1.2

- Fixes password placeholder appearing as bullets in IE7/8/9

## Release notes (v2.1.3)
https://github.com/mathiasbynens/jquery-placeholder/releases/tag/v2.1.3

- Remove sourceMappingURL from uglified version

## Release notes (v2.2.0)
https://github.com/mathiasbynens/jquery-placeholder/releases/tag/v2.2.0

- Fixes password placeholders for password fields not wrapped in a container element

## Release notes (v2.3.0)
https://github.com/mathiasbynens/jquery-placeholder/releases/tag/v2.3.0

- Fixed javascript:void(0) anchor usage from breaking the plugin

## Release notes (v2.3.1)
https://github.com/mathiasbynens/jquery-placeholder/releases/tag/v2.3.1

- Bug fix: Properly exclude [type="hidden"] inputs by using [type="hidden"] rather than :hidden

### CODE REVIEW

**Review by pandaskii — APPROVED** [review]
Ready for testing

**Comment by pandaskii** [comment]
For testing

This file is being used in govcms_zen theme

https://github.com/mathiasbynens/jquery-placeholder

@Venkata-modgu @deanvucic

**Comment by Venkata-modgu** [comment]
Tested with web form using place holder. 
http://586.govcms.xyz/test-placeholder

**Comment by Venkata-modgu** [comment]
Test passed.

**Pull request merged**
