### PR TITLE
Clean up Travis CI

### PR DESCRIPTION
**Pull request by pandaskii**
Remove yml file

### CODE REVIEW

**Comment by aleayr** [comment]
@govCMS/osb-devs Can someone peer review and add a review so I can merge?

**Comment by aleayr** [comment]
This needs to have some conflicts resolved @jozhao

**Comment by pandaskii** [comment]
@aleayr rebase done, cheers

**Comment by seanhamlin** [comment]
Makes sense from my perspective.

**Review by fiasco — APPROVED** [review]

**Comment by tobybellwood** [comment]
test this

**Pull request merged**
