### PR TITLE
Update LinkIt to 7.x-3.5

### LINKED ISSUE #63: LinkIt and Paragraphs compatibility issue
As mentioned in #62, LinkIt is [currently incompatible](https://www.drupal.org/node/2550845#comment-10351297) with editing Paragraphs that have been loaded via ajax.

To reproduce this:
1. Ensure you have a Paragraphs bundle with a field that has a WYSIWYG attached to it
2. Ensure you have a content type with a paragraphs item field with the default edit mode set to "closed" or "preview"
3. Create a new node and add at least one paragraphs item with a wysiwyg
4. Save the node
5. Edit the node, Click "Edit" on the paragraph, Click the LinkIt button

I have submitted a [patch](https://www.drupal.org/node/2550845#comment-10355269) to LinkIt but it has not yet had any response. It is possible to workaround this issue using `hook_element_info_alter()`. 

I will submit two pull requests, one working around the issue in the govcms_editing feature module, and the other applying the patch to LinkIt.

### PR DESCRIPTION
**Pull request by mstrelan**
Fixes #63

### CODE REVIEW

**Comment by mstrelan** [comment]
Is the 5.6 test environment currently broken or is that something wrong with this PR?

**Comment by fiasco** [comment]
@srowlands would know if the environment was broken.

**Comment by aleayr** [comment]
Just a friendly nudge for @srowlands :)

**Comment by stooit** [comment]
Sorry @aleayr, missed this the first time around.

Travis has been a little flaky for us lately, there have been a couple times the build has gone slowly and taken longer for the Behat tests to complete than the default Travis timeout (10 minutes).

When Travis takes a long time to run it really shouldn't matter. I'll submit a new PR to allow for a lengthier timeout period. This is the same issue that caused #150 (and likely others) to fail.

The equivalent build + test cycle takes an average of 5 minutes on the PR environment builder, and frequently in excess of 10 in Travis.

**Comment by aleayr** [comment]
@Venkata-modgu Can I get this tested, would like to merge :)

**Comment by Venkata-modgu** [comment]
Test passed. 
Tested with internal and external links on basic page and blog content. 
Happy to merge this pull request.

**Pull request merged**
