### PR TITLE
Fix issue with LinkedIn and Instagram icons showing by default in the…

### PR DESCRIPTION
**Pull request by seanhamlin**
… social links block. Now users will need to edit the block in order to show them.

### CODE REVIEW

**Review by aleayr — APPROVED** [review]
Paul confirmed looks good.

**Comment by tobybellwood** [comment]
Test this

**Comment by Venkata-modgu** [comment]
Build failed.

**Comment by tobybellwood** [comment]
Test at #622 - 622.govcms.xyz

**Pull request closed without merging**
