### PR TITLE
#199 - add the Multi-path autocomplete module including the patch at …

### PR DESCRIPTION
**Pull request by kurtfoster**
#199 - add the Multi-path autocomplete module including the patch at https://www.drupal.org/node/2418317

### CODE REVIEW

**Comment by fiasco** [comment]
Thanks @kurtsalsa - if you can ensure this gets enabled on install, and provide an update hook to retrospectively enable it for existing customers, then we'll be able to commit this!

**Comment by fiasco** [comment]
Thanks @kurtsalsa!

**Comment by invisigoth** [comment]
@jozhao has discovered this module has an information disclosure flaw as it does not check access properly under certain circumstances. Anonymous users could get access to read information they should not have access to.

For example, it may expose a complete list of existing user accounts (user name and ID) to anonymous users: http://govcms.xing.com.au/mpac/autocomplete/menu/users

@aleayr would you like to discuss this with the security team?

**Comment by pandaskii** [comment]
@aleayr cross-site request (CSRF) is also an issue

I would like to suggest a revert for further investigation

**Comment by aleayr** [comment]
I've reverted this for the moment, let's see if we can get the issue fixed ASAP and get it put back in.

@kurtsalsa Is this something you need for your upcoming release specifically? Talking with @invisigoth and @jozhao, it doesn't seem a big issue to fix the issue above.

**Comment by kurtfoster** [comment]
@aleayr, I don't need this module for anything, it's just a UX failing in Drupal that I've seen people are confused about when I do the govCMS training. I think it would be a good addition. I'm not sure when I'll get time to review the security issues.

**Comment by kurtfoster** [comment]
@aleayr , @jozhao raised the bug on drupal.org here and created a patch https://www.drupal.org/node/2698843. I've made a slight change to the patch but I think it looks good. It's on my branch and I can create another PR if that looks acceptable.

**Pull request merged**
