### PR TITLE
[GOVCMSD7-132] Update redirect 7.x-1.0-rc3 (from 7.x-1.0-rc1)

### PR DESCRIPTION
**Pull request by suhyeonh**
### https://www.drupal.org/project/redirect/releases/7.x-1.0-rc3
Release notes
Changes since 7.x-1.0-rc2:

#2516740 by Dave Reid, DamienMcKenna: Fixed errant logic for watchdog message logic about being unable to purge unused redirects.
#2485459 by Dave Reid: Update hook 7100 does not do a registry rebuild or entity info cache clear.
Use isset() instead of property_exists().
Fixed redirect_fetch_rids_by_path() to fail gracefully if the redirect.status column does not exist yet.
#2516740 by Dave Reid: Avoid watchdog message about being unable to remove unused redirects, if the redirect purge variable is disabled.

### https://www.drupal.org/project/redirect/releases/7.x-1.0-rc2
Release notes
Changes since 7.x-1.0-rc1:

#2308717 by Pere Orga, oadaeh, Kristen Pol: Add watchdog message when inactive redirect purging is enabled, but unable to do so.
#2135575 by mfb, René-Marc Simard: Fixed Views handlers for source and redirect fields were broken.
#1198028 by mxwright, gundarx, chellman: Redirects do not work if $_SERVER['SCRIPT_NAME'] does not follow base_path
#1796596 by stefan.r, Eric_A, Steven Jones, Dave Reid, damien_vancouver, azinck, DamienMcKenna, SylvainM, nicholasruunu, GoZ, deviantintegral, mrmikedewolf, tannerjfco, Yorirou, attila.fekete, vadym.kononenko, heddn, hass, candelas, fenstrat, cmseasy, rooby, vinmassaro, Alan D., hanoii: Fix and prevent circular redirects
#1444506 by helmo, clemens.tolboom, Dave Reid: Fixed users with the "access site in maintenance mode" permission should still be allowed to use redirects.
#2296035 by Pere Orga: Fixed documentation, especially for redirect_load_by_source().
#1872242 by TravisCarden: Fixed typo in redirect_purge_inactive admin form description.
#1913924 by Simon Georges, Dave Reid: Removed useless files[] directive for files that do not contain classes.
#2176175 by fearlsgroove, brad.bulger: Don't add URL redirects to extra fields for excluded entity types.
#2048137 by mfb, Pere Orga, heddn: Disable canonical redirect code that calls drupal_get_path_alias() and breaks path cache (core bug https://www.drupal.org/node/2400539).
#1263832 by hefox, Sneakyvv, scott.allison, Mark Theunissen | grendzy: Fixed Remove session-based flood / loop detection since it performs poorly and has unfix-able race conditions.
#2051313 by mfb, Matt V.: Fixed redirect user ID not stored when redirects added via the user interface.
#2049151 by mauritsl, justanothermark: Fixed vertical summary with number of redirects was incorrect.
Skip infinite redirect loop handling when running in SimpleTests for now.
Removed the crappy redirect loop message and replaced with proper trigger_error() warning.
#1828696 by johannez, Dave Reid: Fixed compatibility with entities that return invalid values for entity_uri().
Fixed redirects could not be created to existing files.
#1244524: Fixed redirect vertical tab table is inconsistent with placement of actions.

### CODE REVIEW

**Review by gargsuchi — DISMISSED** [review]
@suhyeonh1 
- Please make the appropriate changes in composer.json as well 
- Please fix the conflict

**Comment by fubarhouse** [comment]
This PR closes #864.
This PR is a duplicate of #864.

This PR does not need to include any changes to composer.json because it is a Drupal 7 codebase.
To progress this, please resolve conflicts and resubmit or feel free to include #864 in the next release which will close this one. Finalizing this one will also close the duplicate.

**Comment by tobybellwood** [comment]
@fubarhouse - has the backstory issue from https://github.com/govCMS/govCMS/pull/518 (https://github.com/govCMS/govCMS/pull/241) been addressed yet?

**Comment by fubarhouse** [comment]
@tobybellwood,

No, I'll read up on this, do some testing and report back.
I had no idea the background was there.

**Comment by fubarhouse** [comment]
So the problem is that we've applied database update `7101` in a patch, and database update `7101` was introduced in `7.x-1.0-rc2`. The two updates have different purposes where one simply collects a list of table rows to remove and the other will add a field to the table.

A PR will be submitted to govcmslagoon to update the schema to `7100` which will remediate this, and the command will be tested locally. During the `govcms-deploy` script the new changes which add the `status` field will be collected and the PDO Exemption will be mitigated.

It should represent this:
```
drush sql-query "UPDATE system SET schema_version = 7100 WHERE name = 'redirect';"
```

**Comment by fubarhouse** [comment]
Testing and reviewing can now occur based on the changes made available by https://github.com/govCMS/govcmslagoon/pull/76

**Review by ruwanl — APPROVED** [review]

**Pull request merged**
