### PR TITLE
Add hierarchical select module.

### PR DESCRIPTION
**Pull request by invisigoth**
Add hierarchical select module. See https://github.com/govCMS/govCMS/issues/292

### CODE REVIEW

**Comment by invisigoth** [comment]
To test this, log in as administrator and go to modules page. Be sure you can find the hierarchical select module and be able to enable it.

**Comment by aleayr** [comment]
@Venkata-modgu Can you please test this?

**Comment by Venkata-modgu** [comment]
Test passed.
Hierarchical select module added and working.

**Review by aleayr — APPROVED** [review]
Venkata confirms tests passed.

**Pull request merged**
