### PR TITLE
#300 - Consultation module tweaks

### PR DESCRIPTION
**Pull request by Feng-Shui**
This PR contains the following changes to the consultation module:
1. Ensure COMMENT_NODE_OPEN is defined before being used for evaluation
2. Remove used variables in govcms_consultation_preprocess_node()
3. Add module namespace to helper functions
4. Remove return from _govcms_consultation_consultation_vars(), $variables param is passed by reference
5. Set default return value of _govcms_consultation_admin_return_end_consultation_date() to be an int as it’s used in numeric comparison
6. Seed the late submission URL token with the node UUID rather than NID.
7. Refactor _govcms_consultation_admin_return_end_consultation_date() to simplify parameters, `$node` no longer required.
8. Add/update function doc blocks.
9. Remove global $base_url reference in _govcms_consultation_admin_return_late_submission_url() and let url() function handle absolute path.
10. Namespace module constants.

### CODE REVIEW

**Comment by fiasco** [comment]
Would have prefered a few PRs for all of this as there is quite a bit to review and no automated tests to ensure nothing has broken in this change. Will need someone to login into http://305.govcms.xyz/ to test.

**Comment by Feng-Shui** [comment]
If you take a look at the diff,  it's pretty straight forward, most of these commits are one liners and a lot of the changes are actually comments.  You're preaching to the choir re test coverage, I'm adding some in now that I'm working on the functional changes.

**Comment by fiasco** [comment]
I've done some initial testing on the test environment and it doesn't appear to break anything so I'm going to merge this one as its primarily clean-up.

**Comment by Feng-Shui** [comment]
Awesome, thanks @fiasco being able to re-branch from this will make the remainder of the changes much easier.

**Pull request merged**
