### PR TITLE
Update Search Pages module to 7.x.-1.2

### PR DESCRIPTION
**Pull request by barbun**
Search API Pages module needs to be updated to the latest stable version that fixes some important bugs and provides performance improvements. [release notes](https://www.drupal.org/node/2499849)

One particular bug that I came across is this:
https://www.drupal.org/node/2392289

The way to reproduce it:
1) On "Edit search page" page (admin/config/search/search_api/page/default_search) choose a View Mode that is not the default one (e.g. "Teaser")
2) Perform site search for something that won't produce any results
3) On any following page request you will get a warning message

Search API Pages module to 7.x-1.2 fixes the problem with some additional check for search results.

### CODE REVIEW

**Comment by fiasco** [comment]
Looks good to me - @aleayr do we need to have @Venkata-modgu run the test case provided to accept this in?
From my perspective, this is a small change.

**Comment by aleayr** [comment]
I'd like him to.

@Venkata-modgu, can you take a look at the test case, and confirm this solves the issue?

**Comment by Venkata-modgu** [comment]
Test passed. Happy to merge the code.

**Comment by fiasco** [comment]
Thanks for the contribution!

**Pull request merged**
