### PR TITLE
Update Chosen to 1.8.2 (from 1.4.2)

### PR DESCRIPTION
**Pull request by deanvucic**
Release notes

## https://github.com/harvesthq/chosen/releases/tag/v1.8.2
Version 1.8.2
Bugfixes
- Escape optgroup label when appending to HTML.

## https://github.com/harvesthq/chosen/releases/tag/v1.8.1
Version 1.8.1
Bugfixes
-Fix escaping in group names, no results message.
-Fix Chosen for non-ASCII languages
-Only trim input_width to container_width when calculable

## https://github.com/harvesthq/chosen/releases/tag/v1.8.0
Version 1.8.0
Bugfixes
-Don't search HTML escaped text
-Clear search input value, reset results when using hide_results_on_select option

Enhancements
-Use word boundary matching to better match user expectations for searches.
-Remove deprecation warnings on jQuery 3

Packaging
-All compiled source files (including minified) are now included in the package for bower and npm.
-Update dev dependencies to use up-to-date packages

## https://github.com/harvesthq/chosen/releases/tag/v1.7.0
 v1.7.0
From this version on, until further notice, no new features will be added, so pull requests for features will not be accepted. However, pull requests for bugfixes are still very much appreciated.

Bugfixes
-Update regex for highlighting
-Prevent bubbling of escape key
-Escape default text
-Do not clear search text on multi selection
-Unbind label click (#2238), only remove bound events 
-Prevent activation of disabled fields 
-Restore focus after removing an option
-Prevent action on clipboard events when select is disabled
-Focus input in multi select on container click

Features
-Add option to keep results open for multi-select
-Use node-sass for building sass
-Right to Left initialisation option
-Bye bye simulate
-Update implementation regarding Content-Security-Policy

Documentation
-Update README to reflect npm support
-Update the version of jQuery in the docs to the latest 1.X

## https://github.com/harvesthq/chosen/releases/tag/v1.6.2
 v1.6.2
Packaging
-Add PNG files to npm package

## https://github.com/harvesthq/chosen/releases/tag/v1.6.1
v1.6.1
Minor Package Bump
-Fixes tagging on chosen-package

## https://github.com/harvesthq/chosen/releases/tag/v1.6.0
 v1.6.0
Case sensitive search option

Features
-Add option to enable case sensitive search

Bugfixes
-Remove IE 6 hack that clobbered user-defined height overrides
-Update browser support check

Documentation
-Broken link!
-Add contributing templates
-Build process
-A new build process that publishes NPM stuff!

## https://github.com/harvesthq/chosen/releases/tag/v1.5.1
 v1.5.1
Our bower release process has been broken, but a fix may have landed. The only way to find out is to publish a new version and see if bower-chosen picks it up.

Documentation Changes
-Uses a correct word
-Fix a typo

## https://github.com/harvesthq/chosen/releases/tag/v1.5.0
 v1.5.0
-An overdue bump

Features
-Extend mobile browser detection
-Added option max_shown_results

Documentation
-More accurate disable_search_threshold docs
-Add docs for destroying Chosen

Bug Fixes
-Fixes focus highlighting on disabled Chosen
-Properly toggle default class on multi-Chosen
-Fix incorrect "top" linear-gradient syntax
-Calling chosen('destroy') on a non-Chosen element no longer wrongly initializes a new Chosen instance
-Don't open Chosen on option/alt keyup
-Remove unused CSS attribute
-Removes some IE hacks

Build system stuff
-basic test harness in place
-Update bower-chosen to use unminified versions
-Reduce the size of the description for Bower
-Try to keep Bower versions consistent

### CODE REVIEW

**Review by pandaskii — APPROVED** [review]
Ready for testing

**Comment by Venkata-modgu** [comment]
Test failed.

**Comment by tobybellwood** [comment]
@Venkata-modgu what failed?

**Comment by Venkata-modgu** [comment]
Test passed.

**Pull request merged**
