### PR TITLE
Changes the travis file to use their new container based builds, and update the minimum PHP version to 5.5 to run the tests.

### PR DESCRIPTION
**Pull request by typhonius**
Travis has started using containers. _However_, we need to alter the _.travis.yml_ to [get rid of sudo](http://docs.travis-ci.com/user/workers/container-based-infrastructure/).

### CODE REVIEW

**Comment by typhonius** [comment]
This makes me really sad. Containers and drush rs work on PHP 5.5 but not 5.3.

**Comment by typhonius** [comment]
Especially since it halves our test times :sob:

**Comment by typhonius** [comment]
Ah... [this is why](https://secure.php.net/manual/en/features.commandline.webserver.php).

> As of PHP 5.4.0, the CLI SAPI provides a built-in web server.

**Comment by typhonius** [comment]
This should be fixed on or before September 1st when the Acquia platform deprecates PHP 5.2 and 5.3. cc/ @seanhamlin

**Comment by seanhamlin** [comment]
Assigning myself to see if we can raise the minimum requirements for govCMS up to PHP 5.5

**Comment by typhonius** [comment]
:pray:

**Comment by typhonius** [comment]
@seanhamlin this should be unblocked now :open_hands:

**Comment by seanhamlin** [comment]
And both tests pass (PHP 5.5 and PHP 5.6) in under 11 minutes. I don't see any reason why this cannot be merged. Would appreciate input from more people though.

**Comment by aleayr** [comment]
Thanks @typhonius and @seanhamlin for getting this rolling again.

@paulkilla Any objection to merging this in?

**Comment by paulkilla** [comment]
Nope. Go for it 

On 8 Oct 2015 5:13 pm, Adam Leayr notifications@github.com wrote:

Thanks @typhonius and @seanhamlin for getting this rolling again.

@paulkilla Any objection to merging this in?

**Pull request merged**
