### PR TITLE
Add token tweaks module

### PR DESCRIPTION
**Pull request by pandaskii**
Add token tweaks module

ISSUE #201

### CODE REVIEW

**Comment by seanhamlin** [comment]
I would be a big fan of enabling this by default for govCMS installations. Also to minimise the memory usage, you can also set `token_tree_recursion_limit` to 1.

**Comment by fiasco** [comment]
I agree with @seanhamlin, @jozhao could you please add it to the installer, also provide an update hook to install on existing sites and also set `token_tree_recursion_limit` to 1. On a site-by-site basis we can increase that on the SaaS platform if needed.

**Comment by pandaskii** [comment]
No problem working on it

**Comment by fiasco** [comment]
@jozhao we're pretty close. Now we just need to set `token_tree_recursion_limit` which we can do on the platform.

**Pull request merged**
