### PR TITLE
New Consultation feature.

### PR DESCRIPTION
**Pull request by stooit**
Adds a generic implementation of the Department of Communications and the Arts 'Have Your Say' functionality to govCMS (https://www.communications.gov.au/have-your-say)

_Functional scope, documentation & demo environment to follow_

### CODE REVIEW

**Comment by stooit** [comment]
## Brief:

The Consultation feature enables a new content type (Consultation) that allow for public input via formal and informal means against a given topic.

## Functional specs:
- Ability to configure components of Consultation feature
  - Optionally enable Twitter integration (account details required)
  - Optionally enable Disqus commenting (account details required)
  - Optionally enable private submissions (requires opt in)
- Ability to create new consultations, which include the following:
  - Basic details (Title, Summary, Body)
  - Start/End date for a Consultation
  - Related issue documentation (file attachments)
  - Outcomes of a given Consultation
  - Updates/Milestones as a Consultation progresses through lifecycle
  - Ability to enable formal submissions
  - Ability to enable informal submissions
  - Ability to enable accepting late approvals via special URL
  - Ability to specify who should receive email notifications of new submissions
- Formal submissions
  - Can be anonymous (name will not display)
  - Could be private (entire submission will never display)
  - Could be a comment/text only
  - Could include file attachments (.pdf, .doc, .docx by default, configurable)
  - Can be made by individuals or on behalf of a company
  - Each need to be individually approved within govCMS before they will display publicly
  - Approved submissions (that weren’t marked as private) will display against each Consultation
- Informal submissions
  - Twitter discussions
    - manually curated through https://curator.twitter.com/
    - display using Twitters new grid display
  - Disqus comments per Consultation

#### Note:

This module brings a new dependency: [UUID Features](https://www.drupal.org/project/uuid_features). This is required for the Consultation Webform and included taxonomy terms. It's the successor to a module we are already using (Default content) and provides support for a wider range of entities in Drupal.
If this PR is accepted we could look to move the example content modules (govcms_content_*) to use uuid_features instead.

## DEMO:
- [Example completed Consultation](http://150.govcms.xyz/final-consultation-nbn-non-commercial-services-funding-options)
  - as originally seen on [The Department of Communications and the Arts](https://www.communications.gov.au/have-your-say/final-consultation-nbn-non-commercial-services-funding-options)
  - this Consultation has also been configured to allow late submissions via a [special URL](http://150.govcms.xyz/final-consultation-nbn-non-commercial-services-funding-options?fso=2788221432).
- [Example open Consultation accepting formal comments and files](http://150.govcms.xyz/example-consultation-accepting-formal-comments)
  - You can configure to accept either or both
- [Example open Consultation accepting inform comments via Disqus](http://150.govcms.xyz/example-consultation-informal-commenting)
- [Example open Consultation displaying relevant Twitter discussion](http://150.govcms.xyz/example-consultation-twitter-embed)

Documentation: https://github.com/srowlands/govCMS/wiki/govCMS-Consultation

**Comment by Venkata-modgu** [comment]
Attached documents are not displaying on the public site after publishing. But they are displaying after login, is this suppose to work like this?
e.g.: http://150.govcms.xyz/questionnaire

**Comment by fiasco** [comment]
Prior to govCMS issues being discussed on github, we discussed commenting in govCMS and decided:
- govCMS wouldn't support commenting out of the box
- govCMS wouldn't support Drupal comments on the platform
- govCMS wouldn't endorse or support a 3rd party implementation to keep market fair.

Perhaps @teamglenny will want to revisit that but based on my understanding, the discuss integration should come out of the PR.

@srowlands could we have some instruction on how to build a consultation with this PR? Perhaps some creds to login to the test env to dry it ourselves?

**Comment by fiasco** [comment]
### Code Review
- Images added to feature module. What license are these under that we can include them under govCMS which is GPL 2?
- CSS class names are very generic and represent a high risk of conflict with other themes. This can lead to visual bugs when using the consultation module
- LATE_SUBMISSION_SALT is hard set which will make is easy to bypass access controls for late form submissions.
- I cannot find where govcms_consultation_uuid_revert gets set to 0 for govcms_consultation_cron to trigger anymore than once. I'm not quite sure why this is should be implemented in hook_cron. Also, for performance reasons, it would be preferable to use cache_set and cache_get instead of variable_set and variable_get.

**Comment by stooit** [comment]
@Venkata-modgu looks like a bug, will resolve that. Thanks for pointing that out.

@fiasco right you are, will resolve and resubmit. I can provide login details but the environment will be rebuilt when the new PR arrives, so maybe best to just wait. The images were provided by The Dept. of Communications and the Arts. Can double check on license, but I can't imagine it'll be an issue.

I've started fleshing out a guide, will start a wiki page on my fork and provide a link when it's ready to go.

As for Disqus, will need direction from @teamglenny. It was basically a lift of an existing implementation so it got bundled part and parcel. I imagine we could either leave as is, remove entirely or replace with core comments.

**Comment by srowlands** [comment]
test this

**Comment by Venkata-modgu** [comment]
Tested in the new build, attachments are still not displaying on the public site. 
e.g.: http://150.govcms.xyz/consultation-one

**Comment by stooit** [comment]
Hi @Venkata-modgu,
I looked at that; it's actually expected behaviour. govCMS permissions OOTB do not allow anonymous download of Documents/Images/Videos etc, so the links do not display.

I was going to create another issue for that, but it can be resolved with simple site configuration by an administrative user.

**Comment by Venkata-modgu** [comment]
Front end (public site) and back end times are displaying in different time zones for the Consultation.

**Comment by stooit** [comment]
@Venkata-modgu this is site configuration as well -- make sure your user has the same timezone as the global regional date and time setting.

I can see that the site timezone is `Australia/Canberra` while the user was set to `UTC`. I've changed the setting so a user may not override the site timezone to rectify.

**Comment by stooit** [comment]
Documentation wiki page: https://github.com/srowlands/govCMS/wiki/govCMS-Consultation

**Comment by aleayr** [comment]
This looks like we've resolved all outstanding issues?

@srowlands @Venkata-modgu @fiasco Any more thoughts/feedback before we merge this?

@ruwanl Are you happy with the work on this, confirmation from a tech perspective to merge in?

**Comment by fiasco** [comment]
Thanks @srowlands for all the extra effort to make this compatible for govCMS! I think this is ready from a technical standpoint to be merged in and documentation ported to govCMS wiki.

**Comment by aleayr** [comment]
Can I clarify with the Travis tests failing, is this a problem to be addressed before we can merge?

**Comment by stooit** [comment]
@aleayr the Travis failure is due to tests (sometimes) taking longer than 10m to complete and produce output, so it's false negative. I've created an issue (#178) to track, will submit a PR to increase the timeout in Travis soon.

The tests do not fail locally or in the PR environment builder though.

**Comment by cdriessen** [comment]
FYI - I'm just following up on @srowlands previous comment re: image licenses - assuming you still need confirmation on this @srowlands / @aleayr ?

**Comment by fiasco** [comment]
Hi @cdriessen, govCMS uses the GPL v2 open source licence which means any assets such as these images must also be GPL v2 or greater or use a license that supports GPL. Otherwise they cannot be used in the distribution.

**Comment by cdriessen** [comment]
Thanks @fiasco - the image licence info has been provided to Finance for review/advice ( @teamglenny @aleayr )

**Comment by fiasco** [comment]
This pull request needs to be re-submitted against the `7.x-2.x` branch as the master branch has been removed per #226

Apologies for the inconvenience.

**Pull request closed without merging**
