### PR TITLE
Use build:local in Travis to avoid false failures

### PR DESCRIPTION
**Pull request by stooit**

### CODE REVIEW

**Comment by typhonius** [comment]
Do we need to further document the difference between `build:local` and `build:remote` and when you would use each in `README.md`

**Comment by seanhamlin** [comment]
Let's file a follow up ticket to remove build:remote all together (and update the documentation).

**Comment by typhonius** [comment]
I think there's still value in `build:remote` but perhaps only when the user specifically requests it. Ie, not ever in the default path.

**Comment by seanhamlin** [comment]
@typhonius are you happy for that to be in a follow up PR?

**Comment by typhonius** [comment]
Created #29 to deal with this :feet:

**Pull request merged**
