### PR TITLE
Fix bug where disabling Superfish caused PDO exception #206

### PR DESCRIPTION
**Pull request by Feng-Shui**
Re-submitting #210 against 7.x branch.

### CODE REVIEW

**Comment by fiasco** [comment]
@Feng-Shui could you rebase this PR? I can't currently merge it.

**Comment by Feng-Shui** [comment]
@fiasco is there a magic way to rebase the pull request given that I've already pushed my commit?  Or do I have to open a new pull request?

**Comment by Feng-Shui** [comment]
I'll get this one sorted today.

**Comment by fiasco** [comment]
Thanks @Feng-Shui - should be able to merge once ready.

**Comment by Feng-Shui** [comment]
@fiasco Are you able to merge this now?

**Comment by fiasco** [comment]
Perfect thanks!

**Pull request merged**
