### PR TITLE
Update Zen to 7.x-5.6 (from 7.x-5.5)

### PR DESCRIPTION
**Pull request by deanvucic**
## https://www.drupal.org/project/zen/releases/7.x-5.6

Release notes
Fixes the following issues:

#2120355: Images width auto for IE8 cause images to ignore width and height put in markup
#2497005: $zen-reverse-all-floats inconsistent wording?
#2556761: Remove deprecated chrome-frame support
#2448097: panels-pane TPL hardcores H2 tag for every pane label
#2516054: Single form error message not displayed if keyed by element name
#2269461: process_html_tag() breaks angularjs templates
#1084504: PHP Error when secondary menu or menu module is disabled
#2291425: Unpublished not styled properly as watermark
#2058221: New version introduces php warnings.
#1781662: Bad value cleartype for attribute http-equiv on element meta.
#2128643: Infinite loop in zen_preprocess_menu_link()
#2295227: Switch support for FireSass to support to FireCompass
#2323281: Spelling error in zen_no_wrapper layout settings description
#2198637: li.messages__item class improperly escaped
#2333899: Undefined variable $preview for watermark
#1696924: Add Gemfile to control versions of Sass/Compass

### CODE REVIEW

**Comment by pandaskii** [comment]
Blocked this PR after discussion

**Comment by tobybellwood** [comment]
For clarity, the decision to block is based on weighing the volume of testing required to ensure all govcms/zen-based sites would be unaffected against the incremental improvements included in the dot release.

**Comment by deanvucic** [comment]
As discussed in the comments, I am closing this PR.

**Comment by deanvucic** [comment]
As discussed in the comments, I am closing this PR.

**Pull request closed without merging**
