### PR TITLE
SA-CONTRIB-2018-019 - Update ds to 7.x-2.15 (from 7.x-2.8)

### PR DESCRIPTION
**Pull request by tobybellwood**
## https://www.drupal.org/sa-contrib-2018-019

The module doesn't sufficiently validate view modes provided dynamically via URLs leading to a reflected cross site scripting (XSS) attack.

This vulnerability is mitigated only by the fact that most modern browsers protect against reflected XSS via the url.

## https://www.drupal.org/project/ds/releases/7.x-2.15

Release notes
Fixes Critical - Cross site scripting (XSS) - SA-CONTRIB-2018-019

## https://www.drupal.org/project/ds/releases/7.x-2.14

Release notes
- #2503653: Per node template suggestion introduced a regression. This release fixes those problems.

## https://www.drupal.org/project/ds/releases/7.x-2.13

Release notes
- Fix integration for Fieldable Panels Panes.

## https://www.drupal.org/project/ds/releases/7.x-2.12

Release notes
- Bug fix release

## https://www.drupal.org/project/ds/releases/7.x-2.11

Release notes
- Issue #2492661 by Erik Frèrejean: Incorrect field info api documentation for 'block fields'
- Issue #2507163 by aspilicious: Block regions cannot be deleted following upgrade to 2.10
- Issue #2497445 by aspilicious: Upgrading from DS 7.x-2.8 > DS 7.x-2.10 changes view mode on nodes from full content to default on page
- Issue #2493145 by artis: Typo in recent commit for Token support in 7.x-2.x branch
- Issue #2490932: Undefined property: DatabaseConnection_mysql::$sid in node_ds_search_execute() (line 488 of ds_search.module)
- Issue #2453137 by aspilicious: Unable to overwrite theme_ds_field_expert

## https://www.drupal.org/project/ds/releases/7.x-2.10

Release notes
This is a bug fix release for a bug that is affected many websites using ds search. See #2385835: Adding 'theme_hook_original' triggers PHP warning in theme_ds_search_page

## https://www.drupal.org/project/ds/releases/7.x-2.9

Release notes
This release contains various bug fixes and a couple of new features.

New features:
- Enable/disable view modes per content type
- Ability to Disable the CSS file added on Layouts
- Replace tokens in layout attributes

### CODE REVIEW

**Comment by tobybellwood** [comment]
test this please

**Comment by tobybellwood** [comment]
Test this

**Comment by Feng-Shui** [comment]
Just updated DS locally, no issues from what I can see.

**Review by ruwanl — APPROVED** [review]
Approved for testing.

**Comment by Venkata-modgu** [comment]
Test passed.

**Pull request merged**
