### PR TITLE
Update mimemail to 7.x-1.0 (from 7.x-1.0-beta4)

### PR DESCRIPTION
**Pull request by deanvucic**
UPDATE - Patch has been removed in favour of swiftmailer solution in #632 

## https://www.drupal.org/project/mimemail/releases/7.x-1.0

Release notes
The first official release for Drupal 7.

The following patches have been committed since the beta4 release:

Bug fixes

#2743229 by Bird-Kid, AdamPS: CSS doesn't get attached in PHP7
#2858390 by Munavijayalakshmi, Jigar.addweb: Fix coding standard issues
#2594743 by skipyT: Theme function called for plain messages also
#2374673 by smokris: Prevent processing of already embedded images
#2796965 by Cauliflower: Allow NULL values in Rules actions
#2721799 by igorik, sgabe: Minor typo
#2678818 by hoebekewim, das-peter: Mime Mail Compress has a deprecated constructor
#2553815 by nitrocad, anthonys: Imported font generates empty attachment
#2562181 by rrfegade: Remove unused variables
#2562177 by rrfegade: Spelling errors
Features

#1532352 by sgabe, Matt B: Add permission to view user specific settings
#2783815 by argiepiano: Add 'Reply-to' field to "Send HTML mail to all users of a role" action
#2796993 by Cauliflower: Return send status in Rules actions
#1568680 by jamsilver: Use $message for themeing
#2146513 by torotil, Anybody: Scan theme for other *css* file types

### CODE REVIEW

**Comment by tobybellwood** [comment]
Test should include (at a minimum):

Creation of private FS outside docroot
Configure Mailsystem to send emails
Configure Webform to attach files, and save them in private FS
Configure mimemail to use the private path for webform (most likely private://webform)
Configure webform clear to instantly clear
Ensure email arrives with attachment

Environment may need to be configured locally to ensure mail handling.

**Comment by tobybellwood** [comment]
Removed patch to add additional paths - it could introduce unintended vulnerabiities.

**Review by ruwanl — APPROVED** [review]

**Comment by tobybellwood** [comment]
Testing to include:

Continued correct operation of system mails, including webform (but excluding scenario in #616)

**Comment by tobybellwood** [comment]
Test this

**Pull request merged**
