### PR TITLE
Patch Media overlay bug (beta1).

### PR DESCRIPTION
**Pull request by stooit**
Alternate to #133 to patch the currently running Media-beta1 with the backported patch from 2.x-dev.

This may be a more preferable option to updating to 2.x-dev and introducing new, currently unknown change.

### CODE REVIEW

**Comment by aleayr** [comment]
Anyone have an opinion on this verses #133 @jozhao @invisigoth

**Comment by pandaskii** [comment]
@aleayr 
I agree with @srowlands this is more preferable option

**Comment by aleayr** [comment]
@jozhao Good, I'm going to close #133, and focus on this one.

@Venkata-modgu Can we get this tested to ensure the overlay bug is fixed, I'd like to merge.

**Comment by stooit** [comment]
@aleayr any update on this one? It keeps coming up time and time again..

**Comment by Feng-Shui** [comment]
I've been trying to get around to testing this one this week, I'll see if I can take a look at it tomorrow.

**Comment by fiasco** [comment]
This pull request needs to be re-submitted against the `7.x-2.x` branch as the master branch has been removed per #226

Apologies for the inconvenience.

**Pull request closed without merging**
