### PR TITLE
Added new module taxonomy_manager (7.x-1.0)

### PR DESCRIPTION
**Pull request by tobybellwood**
From discussion in https://community.govcms.gov.au/t/taxonomy-manager-module/886?u=tobybellwood

### CODE REVIEW

**Comment by xtfer** [comment]
This is a bit of a no-brainer. No public functionality, it's just a UI to reorder, merge and reparent taxonomies. Essential if you have a large taxonomy. Unless it has any outstanding security issues or doesn't work with the admin theme, I would recommend adding it.

**Comment by Venkata-modgu** [comment]
Test partially passed.

**Comment by Venkata-modgu** [comment]
One minor issue found - search not returning results form children.

**Review by ruwanl — APPROVED** [review]
Module seems to be actively maintained and cannot see any outstanding security issues.  The port for D8 is underway but no alpha release yet but there is activity in the more recent days.

Installation of module did not have any build issues or compatibility issues.

**Pull request merged**
