### PR TITLE
github.com #289 - Add LICENSE.txt

### PR DESCRIPTION
**Pull request by ghost**
For the four freedoms.

### CODE REVIEW

**Comment by aleayr** [comment]
Thanks @agileware - Should we have this in plain text rather than HTML do you reckon?

**Comment by agileware** [comment]
Good catch @aleayr - Can't believe I did that.

**Comment by agileware** [comment]
Updated PR - Apologies for confusing commit changes, felt it was probably better to rebase a fresh copy as the previous commit was _completely wrong_

**Comment by aleayr** [comment]
Thanks @agileware - Looks much better, no issues with the commit history.

@fiasco Any idea why the build environment is failing? It's only the addition of a file. You merged #286 this morning, are you able to check the Jenkins logs and see if this is causing the issue?

**Comment by fiasco** [comment]
Build bot built fine in the end. Confirmed License is identical to Drupal's. Thanks for the contribution @agileware !

**Pull request merged**
