### PR TITLE
Update ClamAV to 7.x-1.0-beta1

### PR DESCRIPTION
**Pull request by mstrelan**
A new version of ClamAV was released today which includes the patch that was previously applied to scan all files, not just filefields.

### CODE REVIEW

**Comment by mstrelan** [comment]
Looks like this release is too recent for the build

```
Downloading release history from                                        [notice]
https://updates.drupal.org/release-history/clamav/7.x
/home/travis/.drush/cache/download/https---updates.drupal.org-release-history-clamav-7.x   [notice]
retrieved from cache.
Could not locate clamav version 7.x-1.0-beta1.                           [error]
```

**Comment by fiasco** [comment]
yeah, travis caching is a pain! but govcms bot succeeded.

**Comment by fiasco** [comment]
I'm OK with having this merged. The one patch we were tracking was accepted into govCMS.

**Comment by pandaskii** [comment]
No problem on having this merged after #116 @aleayr

**Comment by aleayr** [comment]
I tihnk I'll merge it now, and we can decide later on the ClamAV, plus other associated modules as to their usefulness inside/outside the base distro.

**Pull request merged**
