### PR TITLE
SA-CONTRIB-2018-013: Update entity to 7.x-1.9 (from 7.x-1.8)

### PR DESCRIPTION
**Pull request by tobybellwood**
## https://www.drupal.org/project/entity/releases/7.x-1.9

This release is a security release. See Entity API - Moderately critical - Information Disclosure - SA-CONTRIB-2018-013 for more information.

Changes since 7.x-1.8:

Improve debug output of entity metadata wrapper exceptions.
#2807275 by anrikun: Notice : Undefined property: stdClass::$nid in node_access()
#2455361 by PieterDC: Don't flush Entity Cache tables that aren't created yet
#2090007 by danielnolde: EntityDrupalWrapper::getIterator() throws PHP error: EntityMetadataWrapperIterator::__construct() must be an array
#1957266 by Anybody, arx-e, Jelle_S, stBorchert, Deciphered, awolfey: Rendered entity in views header accepting arguments from URL

### CODE REVIEW

**Comment by mgdhs** [comment]
https://www.drupal.org/sa-contrib-2018-013

> The module prints debugging information to the HTML output in certain error conditions thereby causing an information disclosure vulnerability.
> This vulnerability is mitigated by the fact that an attacker needs to be able to trigger the error condition in a way that protected data is exposed.

**Review by pandaskii — APPROVED** [review]
Happy to be merged after testing

**Comment by tobybellwood** [comment]
Testing to include:

Correct operation of the entity module.

**Comment by Venkata-modgu** [comment]
Test passed.

**Pull request merged**
