### PR TITLE
Allow for WYSIWYG enabled webform textarea fields.

### PR DESCRIPTION
**Pull request by stooit**
This module provides a new Webform field type (HTML textarea). It allows for WYSIWYG enabled fields on Webform submissions.

The Department of Communications and the Arts are looking to extend their 'Have Your Say' functionality by allowing for short formal submissions using this module. This would allow those submissions to contain basic markup and improve readability and display.

screen shot 2015-10-29 at 12 55 21 pm

### CODE REVIEW

**Comment by teamglenny** [comment]
Have been involved with the Comms discussions.  This will enable a visitor to use basic formatting for webform fields which will ultimately be dropped into another system that requires html formatting.  See other agencies wishing to have this feature: [wiki article](https://github.com/govCMS/govCMS/wiki/Contributing-to-govCMS).

**Comment by stooit** [comment]
test this

**Comment by stooit** [comment]
You can check a demo of this out on the PR environment:
  http://govcms-pr87.52.64.233.163.xip.io/example-wysiwyg-enabled-webform

**Comment by teamglenny** [comment]
From the end user perspective it seems to be the beans :)

**Comment by teamglenny** [comment]
@srowlands will the simple formatting be the same as the screenshot you posted in this thread? The PR environment doesn't have bullet or numbered lists, probably more useful that the horizontal line?

**Comment by stooit** [comment]
@teamglenny This is entirely configurable, you can restrict the textarea to using a specific text formatter (which can have its own restrictions on tags, WYSIWYG profile config, etc).

**Comment by fiasco** [comment]
This has been tested by @teamglenny and produced by @srowlands - so both gov and tech stakeholders are happy - I think we can merge this.

**Pull request merged**
