### PR TITLE
#199 - Added patches to the mpac module

### PR DESCRIPTION
**Pull request by pandaskii**
#199 - Added patches to the mpac module

### CODE REVIEW

**Comment by fiasco** [comment]
I'm not sure `administer menus` is the right permission to be using?

**Comment by aleayr** [comment]
This hasn't had a chance to be fully tested due to competing workloads, pushing back to 2.5.

**Comment by aleayr** [comment]
@jozhao This might be a good candidate for some behat tests to automate the testing process.

**Comment by aleayr** [comment]
@Venkata-modgu Please test this one :)

**Comment by fiasco** [comment]
This is a good candidate for behat tests.

**Comment by Venkata-modgu** [comment]
Test passed.

**Pull request merged**
