### PR TITLE
Update linkchecker to 7.x-1.3 (from 7.x-1.2)

### PR DESCRIPTION
**Pull request by deanvucic**
## https://www.drupal.org/project/linkchecker/releases/7.x-1.3

Release notes
#2060243: Split linkchecker_scan_nodetypes as content type specific
#2651180: Ignore fragment used for ajax requests
Upgrade outdated HTTP user agents.
#2660694: PHP 7.0 errors
Fixed two typos
#2443055: Optionally reduce the number of LinkChecker log entries
#2616082: Add @return type and @param values in the comment docblocks.
#2303177: "Back to Top" Page anchor being reported as a 404 error?
#2340211: Error on adding content submission

Includes updated patch (124) for 1.3 release:
https://www.drupal.org/node/965720

### CODE REVIEW

**Comment by tobybellwood** [comment]
Test this

**Comment by tobybellwood** [comment]
looks like patch application from https://www.drupal.org/node/965720 still fails - to investigate

**Comment by gargsuchi** [comment]
Can we close this in favor of https://github.com/govCMS/govCMS/pull/757
@tobybellwood

**Comment by tobybellwood** [comment]
closing this in favor of #757

**Pull request closed without merging**
