### PR TITLE
Feature/issue 377 paragraphs deletes content

### PR DESCRIPTION
**Pull request by NigelCunningham**
This patch adds the patch from https://www.drupal.org/node/2603424, comment 19 to govCMS, fixing an issue with the paragraphs module deleting content under some circumstances. The steps to reproduce are based on the issue itself:

Make a fresh govCMS install.
Enable the Paragraphs module.
Create a bundle paragraph with some fields.
Create a second bundle with a paragraph field that accepts the first bundle with multiple values.
Create a content type and put a paragraph field that accepts the second bundle.
Create a node with only one item inside the field and publish it using workbench moderation.
Create a new draft of that published node and add another item on the paragraph field. Save it as a draft.
Re-edit the new draft just created. The only sign that you added another item in the previous step will be a drag handle and the associated extra space taken - you won't see or be able to edit the data entered for the new item.

Associated issue: #377

### CODE REVIEW

**Comment by dataphage** [comment]
Hi Folks

We really need this for the National Film and Sound Archive build which goes live this Friday!!!

Have been asked to CC @aleayr

**Comment by NigelCunningham** [comment]
Morning all. Just wanted to check whether there's anything I can do to help progress this.

**Comment by aleayr** [comment]
Hi @NigelCunningham, apologies, I was off unwell yesterday.

@govCMS/osb-devs Can someone take a look into this and give me feedback?

@dataphage Unfortunately, this change won't be available by Friday. We need to have this fully tested, and given that the community doesn't seem to have a consensus as to the best patch to use in https://www.drupal.org/node/2603424, and despite being marked critical, is still listed as 'Needs Work'. We need to tread carefully on this one, while still trying to help solve this as soon as possible.

**Comment by aleayr** [comment]
In particular, if someone could take a look at why the build server failed on this change, that would be appreciated.

**Comment by NigelCunningham** [comment]
Thanks for the reply Adam. I was mostly wondering about the failures, but given I'm busy getting the project ready for go-live, perhaps I shouldn't offer too much! :)

**Comment by seanhamlin** [comment]
The build failed due to there being security updates needed for govCMS

```
 Workbench            7.x-1.4            7.x-3.0           SECURITY UPDATE 
Execution of target "test:security-updates" failed for the following reason: /var/lib/jenkins/jobs/govcms_pull_request_builder/workspace/379-actual/build/phing/build.xml:345:10: Task exited with code 1

BUILD FAILED
/var/lib/jenkins/jobs/govcms_pull_request_builder/workspace/379-actual/build/phing/build.xml:345:10: Task exited with code 1
Total time: 1.8198 second
```

My question for the people of this thread - if we update to workbench_moderation 7.x-3.0, does this mean that this patch is still required?

**Comment by NigelCunningham** [comment]
I believe it will still be needed - it's a patch against paragraphs, not workbench moderation. Having said that, I haven't checked.

**Comment by NigelCunningham** [comment]
Hi all.

Just wondering if we can do anything to help this along.

Regards,

Nigel

**Comment by aleayr** [comment]
Noting that I intend to merge this into the next release (2.11).

Can @govCMS/osb-devs and @Venkata-modgu ensure testing completed.

**Comment by aleayr** [comment]
@Venkata-modgu has confirmed testing has passed for this patch. The patch fixes the issue indicated above.

Site Editors/Site Builders will still need to be assigned permission via the module_permissions interface for administering both the Paragraphs and Paragraph Bundle UI modules and permissions so that new bundles can have appropriate permissions added to users (such as view to anonymous users, create/edit to Site/Content Editors etc).

**Review by aleayr — APPROVED** [review]
Approved.

**Pull request merged**
