### PR TITLE
[issue 486] - Added the seckit patch, https://www.drupal.org/files/is…

### PR DESCRIPTION
**Pull request by kurtfoster**
…sues/seckit-script-error-in-ie-2374803-4-7.x.patch, to deal with the socket IE issue.

### CODE REVIEW

**Review by seanhamlin — CHANGES_REQUESTED** [review]
Please comment on the d.o issue with

* steps to reproduce
* error seen by end user
* what the patch does to resolve it
* mark it RTBC if you are happy with the patch

I would much rather bump seckit then add this patch, but if must do this sooner rather than later, knowing the timeline would be helpful.

**Comment by kurtfoster** [comment]
@seanhamlin , I've updated the issue on d.o. with the details you requested and marked it as RTBC. This is what's on the d.o issue now:

@wiifm
<ol>
   <li>steps to reproduce</li>
  <li><ol>
        <li>Enable JavaScript + CSS + Noscript protection in seckit</li>
       <li>Create a Paragraphs field</li>
        <li>Enable 'Embedded' widget on that field</li>
        <li>Attempt to add a new item in IE9 or 10</li>
       <li>Also see my comments above in #3. The other issue is the closing tag just isn't there, which is what the patch in #4 fixes.</li>
   </ol></li>
  <li>error seen by end user</li>
     <ol>
        <li>The user just see the throbber continuing to spin, in tha background there's an ajax error.</li>
     </ol>
  <li>what the patch does to resolve it
      <ol>
         <li>The patch just closees the comment tag inside the <script> properly. </li>
      </ol>
   </li>
</ol>

**Review by pandaskii — CHANGES_REQUESTED** [review]
The patch itself is light and small. However, for the particular IE 9 and 10 issue, would like to hear back from more testing and scenarios.

Regarding the feature "JavaScript + CSS + NoScript protection", the following tests are required:
1. Confirm IE 9 and IE 10 issue fixed
2. Major browsers (Edge, Chrome, Firefox, and Safari) are well running with this patch applied

I will assign this PR to our tester @Venkata-modgu

**Comment by pandaskii** [comment]
Many many years ago, CDATA section was used in javascript and inline javascript was added [CDATA] by the drupal core. 

The structure of CDATA section in Drupal is like

```
<script type="text/javascript">
<!--//--><![CDATA[//><!--
    ...
//--><!]]>
</script>
```

Zen theme in Drupal removed this CDATA section, please check zen_process_html_tag
```
  if ($tag['#tag'] == 'style' || $tag['#tag'] == 'script') {
    // Remove redundant type attribute and CDATA comments.
    unset($tag['#attributes']['type'], $tag['#value_prefix'], $tag['#value_suffix']);

    // Remove media="all" but leave others unaffected.
    if (isset($tag['#attributes']['media']) && $tag['#attributes']['media'] === 'all') {
      unset($tag['#attributes']['media']);
    }
  }
```

Many govCMS sites are using `Zen` as a base theme, and it is widely used in many other themes to remove the CDATA comments

The current code snippet with this feature in seckit module is expecting that inline javascript always contains the CDATA comments section as this
```
<!--//--><![CDATA[//><!--
    ...
//--><!]]>
```

Most of latest major browsers can fix this error automatically but IE 9 and 10 are without such ability.

**Review by pandaskii — CHANGES_REQUESTED** [review]
The current patch may break the sites which are having CDATA comments section within inline javascript. Please check the background here https://www.drupal.org/node/2374803#comment-12091664

And we need to add this into testing list

**Comment by pandaskii** [comment]
@kurtsalsa There is no "Inline Entity Field" widget in govCMS Drupal 7 distribution.

Seems that this widget is provided by the module "Inline Entity Form" (not in govCMS Drupal 7 distribution)

Modules, themes and libraries in govCMS Drupal 7 Distribution can be found here https://github.com/govCMS/govCMS/blob/7.x-2.x/drupal-org.make

**Comment by tobybellwood** [comment]
Changed milestone owing to Block

**Comment by kurtfoster** [comment]
@pandaskii, I don't understand the comment in relation to 'Inline Entity Field'. This module is not installed on the budget website and is not related to this issue, it is only an issue between SecKit and IE9. I have outlined the steps to reproduce in [this comment](https://github.com/govCMS/govCMS/pull/487#issuecomment-299744298)

I am unsure how you want me to proceed with this?

**Comment by pandaskii** [comment]
@kurtsalsa Our tester was trying to reproduce the issue following the instructions/steps in comment https://github.com/govCMS/govCMS/pull/487#issuecomment-299744298

From step 2 iii

> Enable 'Inline Entity Field' widget on that field

There is no "Inline Entity Field" widget in govCMS Drupal 7 distribution can be found. Therefore, our tester cannot reproduce this issue on the testing govCMS site with the steps provided in the comment.

**Comment by kurtfoster** [comment]
@pandaskii, Sorry, I realised that description was incorrect, I've fixed it now, it's actually Paragraphs Embed.

**Comment by pandaskii** [comment]
Dear @Venkata-modgu please check the revised reproduce steps in this comment https://github.com/govCMS/govCMS/pull/487#issuecomment-299744298

**Comment by fiasco** [comment]
Conversation in D.O seems to be going nowhere. How relevant is this still to govcms?

**Comment by kurtfoster** [comment]
@fiasco , this still causes an issue in govCMS. There is an HTML comment that is opened and never closed. I'm not sure what harm it can cause to close the comment. That's all that IE requires to work. Other browsers are more capable of dealing with the issue.

**Comment by tobybellwood** [comment]
test this

**Comment by tobybellwood** [comment]
test this

**Comment by Venkata-modgu** [comment]
test this

**Comment by barbun** [comment]
Test this

**Comment by barbun** [comment]
Test this

**Comment by barbun** [comment]
This passes the tests, however, due to recent updates in Jenkins the "default" state that is marked as failed is no longer valid and won't be used for future PRs.

Not sure if "default" check can be removed manually for this (and other open) PR?

**Comment by deanvucic** [comment]
This will be considered for future milestones. For now, I'm closing this PR.

**Pull request closed without merging**
