### PR TITLE
Upgrade govcms_ckan to 1.3.

### PR DESCRIPTION
**Pull request by stooit**
Bumps the `govcms_ckan` module to the new 1.3 release.

As per the release notes (https://www.drupal.org/project/govcms_ckan/releases/7.x-1.3):

The 1.3 release introduces new functionality and bug-fixes to govCMS CKAN.

- Added views handler for CKAN datasets, with support for dynamic queries (steveworley)
- Added new visualisation type: Bubble Chart (steveworley)
- Support for CKAN instances < 2.3 (kurtsalsa)
- Support for Drupal installs with a non-root basepath (kurtsalsa)
- Fixed requirement for auth-header config (jez500)

cc @tobybellwood @kurtsalsa

### CODE REVIEW

**Comment by srowlands** [comment]
test this

**Review by pandaskii — COMMENTED** [review]
Looks ok to me. Happy to merge after testing by @Venkata-modgu 

Cc @invisigoth @ruwanl

**Comment by tobybellwood** [comment]
test this

**Comment by tobybellwood** [comment]
test this

**Comment by Venkata-modgu** [comment]
Test passed.

**Review by tobybellwood — APPROVED** [review]
Tests passed - approved

**Pull request merged**
