### PR TITLE
Update media module to 2.1 (security).

### PR DESCRIPTION
**Pull request by seanhamlin**
Fixes https://github.com/govCMS/govCMS/issues/496

### CODE REVIEW

**Comment by seanhamlin** [comment]
2.3 release notes https://www.drupal.org/project/media/releases/7.x-2.3

**Review by invisigoth — COMMENTED** [review]
I have reviewed the following and am happy for this PR to be passed onto our tester to test before release.

Release notes: https://www.drupal.org/project/media/releases/7.x-2.3

Commits: https://www.drupal.org/node/19304/commits

**Comment by Venkata-modgu** [comment]
Test passed.

**Review by pandaskii — APPROVED** [review]
@invisigoth has reviewed the changes and test passed by @Venkata-modgu

**Comment by Venkata-modgu** [comment]
test this

**Pull request merged**
