### PR TITLE
Patch Media overlay bug (dev branch).

### LINKED ISSUE #132: Media browser dialog opens twice for image fields
When using the Media Browser on an image field the overlay opens twice, and you cannot select images until you close the top overlay (an error "You have not selected anything!" is thrown).

This issue has been replicated on production sites and a vanilla local install of govCMS master. It looks like this issue was introduced recently, but I haven't dug into by what.

This is a duplicate of the issue posted on Drupal.org (https://www.drupal.org/node/2534724).

Pull request incoming to incorporate patch 53 from the d.o issue.

### PR DESCRIPTION
**Pull request by stooit**
Resolves #132 

Currently multi-cardinality image fields using the 'Media Browser' plugin will trigger the overlay to load twice, and disallow selection of any images until one of the overlays are closed.

This patch resolves the issue and has already been adopted by other big distributions (Panopoly -- see d.o issue https://www.drupal.org/node/2534724)

### CODE REVIEW

**Comment by aleayr** [comment]
Posted this in the issue as well, but for posterity: can we roll the patch from 72 instead, looks to be the one the community believes is the best fix for a few broader issues.

**Comment by stooit** [comment]
Replaced with patch from #72.

**Comment by stooit** [comment]
As indicated by the failures:

```
 * [@self.0] Unable to patch media with                                  [error]
media-browser_opens_twice-2534724-72.patch.
```

Will see what the issue is here.

**Comment by stooit** [comment]
@aleayr patch 72 requires 2.x-dev (we're running 2.0-beta1).

So, 2.x-dev with 72, or 2.0-beta1 with 53?

I think we fall back to the previous patch to immediately resolve. #72 will likely be rolled into a stable release in due course, so during a future upgrade this patch will become redundant anyway. Worth noting that others (e.g Panopoly) are using 53 too.

**Comment by stooit** [comment]
Seems ok on rebuild @aleayr, looks ok on the demo environment (133.govcms.xyz) with that patch in place.

**Comment by aleayr** [comment]
@invisigoth @jozhao Can either of you review and confirm if you're happy from a dev perspective to merge this in?

**Comment by pandaskii** [comment]
@aleayr maintainer of Media module Dave Reid just committed a new patch to [Media module dev branch](http://cgit.drupalcode.org/media/commit/?id=89287f76df1ff24409b3ec474c59218929385733) and said "[this is a version that applies to 7.x-2.0-beta1](https://www.drupal.org/node/2534724#comment-10858224)"

This patch [#88](https://www.drupal.org/files/issues/2534724-beta1-backport-do-not-test.patch) is adopted from [#72](https://www.drupal.org/files/issues/media-browser_opens_twice-2534724-72.patch) with small tweaks (An IE8 issue has been raised with this patch)

**Comment by aleayr** [comment]
Nice! An official solution is a good solution in my book. Are there any other changes in the dev branch release that people would be concerned about? Since this is an admin side issue, I don't think I'm that concerned about IE8 compatibility. Thoughts?

**Comment by stooit** [comment]
@aleayr updated to that specific commit of the 2.x-dev branch. Looks good in the PR environment.

I don't see anything major from 2.x-dev in the issues queue that applies to us, but that's not to say there hasn't been change. I'll submit a second PR that just patches the current beta1 with the [backported patch](https://www.drupal.org/files/issues/2534724-beta1-backport-do-not-test.patch) so both options can be considered.

**Pull request closed without merging**
