### PR TITLE
Changing .DS_Store? to .DS_Store

### PR DESCRIPTION
**Pull request by alex-page**
Changing .DS_Store? to .DS_Store so it correctly ignores the .DS_Store file.

### CODE REVIEW

**Comment by Feng-Shui** [comment]
I had `.DS_Store` in my global `.gitignore`, when removing it `.DS_Store` files appear in git status.  Suggests that the version in govCMS did had an issue.

**Review by seanhamlin — APPROVED** [review]
Seems like a great easy change. I did a grep through the codebase, and there appears to only be DS_Store files in contrib modules (nothing in govCMS). So I am happy with this commit.

**Comment by pandaskii** [comment]
@tobybellwood May I suggest this PR in the next release?

**Review by fiasco — APPROVED** [review]

**Comment by fiasco** [comment]
test this

**Comment by fiasco** [comment]
test this

**Comment by fiasco** [comment]
test this

**Comment by srowlands** [comment]
test this

**Comment by fiasco** [comment]
test this

**Pull request merged**
