### PR TITLE
Security release for metatag, also update patch (still applies).

### PR DESCRIPTION
**Pull request by seanhamlin**
See https://www.drupal.org/project/metatag/releases/7.x-1.21 and https://www.drupal.org/node/2852937

Fixes https://github.com/govCMS/govCMS/issues/434

### CODE REVIEW

**Comment by seanhamlin** [comment]
Tested the patch still applies (just):

```
$ patch -p1 < metatag-n1970362-60.patch
patching file metatag.migrate.inc
patching file metatag.module
Hunk #1 succeeded at 280 (offset 1 line).
Hunk #2 succeeded at 1250 (offset 12 lines).
Hunk #3 succeeded at 1259 (offset 12 lines).
Hunk #4 succeeded at 1413 (offset 15 lines).
Hunk #5 succeeded at 1436 (offset 15 lines).
Hunk #6 succeeded at 2281 (offset 41 lines).
patching file metatag.vertical-tabs.js
patching file metatag_advanced_attributes/metatag_advanced_attributes.inc
patching file metatag_advanced_attributes/metatag_advanced_attributes.info
patching file metatag_advanced_attributes/metatag_advanced_attributes.module
patching file metatag_advanced_attributes/tests/metatag_advanced_attributes.test
patching file metatag_dc/metatag_dc.metatag.inc
patching file metatag_panels/metatag_panels.module
```

**Comment by seanhamlin** [comment]
Seeing a few errors on the CI env:

```
Notice: Undefined index: value in DrupalTextMetaTag->getValue() (line 303 of /var/lib/jenkins/jobs/govcms_pull_request_builder/workspace/471-actual/docroot/profiles/govcms/modules/contrib/metatag/metatag.inc).
```

**Comment by seanhamlin** [comment]
Error has gone away which is great.

**Comment by seanhamlin** [comment]
All seems OK, I created a test news article http://471.govcms.xyz/news-media/news/test-article with some example metatags

**Review by fiasco — APPROVED** [review]

**Comment by aleayr** [comment]
I can double confirm that I'm happy with testing as well, this looks good.

**Pull request merged**
