### PR TITLE
Update better_exposed_filters to 7.x-3.5 (from 7.x-3.4)

### PR DESCRIPTION
**Pull request by deanvucic**
## https://www.drupal.org/project/better_exposed_filters/releases/7.x-3.5
Release notes

Fixes XSS vulnerability reported in #2918762: XSS issues with "Enable secondary exposed form options" for users with Administer Views permissions.

### CODE REVIEW

**Comment by pandaskii** [comment]
Restart the checks

**Review by pandaskii — APPROVED** [review]
Ready for testing

**Comment by Venkata-modgu** [comment]
Build failed.

**Comment by tobybellwood** [comment]
Test this

**Comment by tobybellwood** [comment]
Build fixed!

**Comment by Venkata-modgu** [comment]
Test failed. 
I am able to reproduce issue https://www.drupal.org/project/better_exposed_filters/issues/2918762 in PR environment.

**Comment by tobybellwood** [comment]
I've double checked, and this is the expected behaviour - 3.5 strips the <script> tags and displays the text, 3.4 runs the script.  Notes in GOVCMSDEV-489

**Comment by Venkata-modgu** [comment]
Test passed, this is expected behaviour.

**Pull request merged**
