### PR TITLE
#145 - Added views support to Linkchecker via a patch

### PR DESCRIPTION
**Pull request by kurtfoster**
I've made some minor updates to the patch [here](https://www.drupal.org/node/965720) based on this [issue](https://github.com/govCMS/govCMS/issues/145).

### CODE REVIEW

**Comment by fiasco** [comment]
Thanks Kurt, do you think there might be performance implications of this? Is there some reasonable limits you could advise on using this feature?

**Comment by kurtfoster** [comment]
@fiasco, what performance concerns do you have?

I created some sample data, around 300 broken links. I ran XHProf on the old and new report, the views page takes about 5MB more (~25 for views vs ~20 for standard) for the full page load.

**Comment by fiasco** [comment]
Im interested to know if the SQL queries get slow when the broken link count sky rockets (for example, 10k).

**Comment by kurtfoster** [comment]
@fiasco ok, makes sense, I'll do some profiling when I get some time.

**Comment by Feng-Shui** [comment]
We've got over 10k rows in `admin/reports/linkchecker_adv`

screen shot 2016-03-17 at 3 40 20 pm

**Comment by Feng-Shui** [comment]
I'm also seeing similar memory usage to @kurtsalsa in xhprof too.

**Comment by fiasco** [comment]
Thanks @Feng-Shui - I'm satisfied by that data. When the conflict is resolved, we can merge.

**Comment by fiasco** [comment]
thanks @kurtsalsa!

**Pull request merged**
