### PR TITLE
Added views_datasource module

### PR DESCRIPTION
**Pull request by aleayr**
#461

### CODE REVIEW

**Comment by aleayr** [comment]
Testing has passed.

**Review by govhosting — APPROVED** [review]

**Comment by aleayr** [comment]
Whoops, wrong issue commented on. I'll revert this, should be in the subsequent release.

**Comment by aleayr** [comment]
Given this is a very minor change to the output options for Views (allows JSON and XML in read only format) in addition to the RSS that is already there, I might just get Venkata to test this in the test environment so I don't have to do a revert at this stage.

**Comment by Venkata-modgu** [comment]
Test passed.

**Pull request merged**
