### PR TITLE
Update Paragraphs to 7.x-1.0-rc3 and apply patch to fix #2562875

### PR DESCRIPTION
**Pull request by mstrelan**
Patch fixes [Paragraphs bundle access breaks on draft revisions](https://www.drupal.org/node/2562875) and update removes some PHP notices. 

The patch has been committed to dev. Does GovCMS track this and update to the next version to reduce the number of patches?

### CODE REVIEW

**Comment by fiasco** [comment]
I think there is a preference to track releases over patches. @murraywoodman would you be able to make a release of Paragraphs?

**Comment by fiasco** [comment]
No update from @murraywoodman. I'm happy for this to be merged. @srowlands you're probably best person to know the impacts of this - any objections?

**Comment by stooit** [comment]
Looks good to me @fiasco, I'll merge after quickly testing on one of our Paragraph-heavy sites.

**Comment by stooit** [comment]
Thanks @mstrelan, merged and closing.

**Pull request merged**
