### PR TITLE
Update feeds to 7.x-2.0-beta3 (from 7.x-2.0-beta1)

### PR DESCRIPTION
**Pull request by barbun**
GovCMS currently sports outdated Feeds module (beta 1) that was released 1.5 years ago. Since then there were two new releases (beta2 and beta3) with the updates that provide a lot of value. (drush support, new targets and processors, entity translation support and many small but important bug fixes and improvements) 

More information here:
https://www.drupal.org/project/feeds/releases

On the side note, now with agencies moving towards open data (e.g. data.gov.au) Feeds becomes an important player in the field.

### CODE REVIEW

**Comment by aleayr** [comment]
Boom, let's get this tested :+1:

**Comment by seanhamlin** [comment]
Not having this tested and merged in impacting at least 1 site on govCMS SaaS. Acquia ticket #396391. Glad to see the 2.14 milestone attached to it.

**Comment by tobybellwood** [comment]
Test This

**Review by Venkata-modgu — APPROVED** [review]
reviewed by @ruwanl

**Comment by tobybellwood** [comment]
Test This

**Comment by tobybellwood** [comment]
closing in favour of #542 - that builds correctly

**Pull request closed without merging**
