### PR TITLE
Security updates April 2017

### PR DESCRIPTION
**Pull request by seanhamlin**
Also removes the legal module as this is not a great fit for govCMS.

Also of note is the fact that the security check now should pass in Jenkins.

Note this PR should fix the following issues:

* #489 (Scheduler module update PR)
* #488 (Scheduler module update)
* #485 (Scheduler workbench module)
* #441 (Scheduler module update)
* #388 (Jenkins failure)

### CODE REVIEW

**Comment by seanhamlin** [comment]
[Jenkins log is here](http://13.55.162.17:8000/job/govcms_pull_request_builder/334/consoleFull). @srowlands has also fixed up the URL in the "details" section below to actually point at the correct EIP.

**Comment by klonos** [comment]
@seanhamlin you might wanna include https://github.com/govCMS/govCMS/pull/494 that fixes https://github.com/govCMS/govCMS/issues/493

**Comment by seanhamlin** [comment]
Hey @klonos, this PR is supposed to be security related module updated only. I included scheduler in the mix, as scheduler_workbench is in this list (and highly coupled modules usually like to be updated together).

Looking at https://www.drupal.org/project/userprotect/releases/7.x-1.2 it is a bug fix release only. So your PR is still valid there.

**Review by aleayr — APPROVED** [review]
Testing passed.

**Comment by klonos** [comment]
Sorry, I missed your comment @seanhamlin. Yes, fair enough. Thanx for testing and merging @aleayr

**Pull request merged**
