### PR TITLE
Upgrade pathauto_persist to latest stable.

### PR DESCRIPTION
**Pull request by stooit**
This resolves the current issue with govCMS master not building correctly (as of 25th September).

The change between the version of 7.x-dev that we were running and 7.x-1.4 stable is minimal, introducing only some additional performance enhancements via caching.

Full diff below:

```
7,8c7,8
< ; Information added by Drupal.org packaging script on 2015-09-25
< version = "7.x-1.4"

---
> ; Information added by Drupal.org packaging script on 2014-05-09
> version = "7.x-1.3+1-dev"
11c11
< datestamp = "1443213544"

---
> datestamp = "1399606427"
diff pathauto_persist/pathauto_persist.module /apps/govcms-Core/docroot/profiles/govcms/modules/contrib/pathauto_persist/pathauto_persist.module
7,20d6
<   // Statically cache which entity types have data in the pathauto_persist
<   // table to avoid unnecessary queries for entities that would not have any
<   // data anyway.
<   static $loadable_types;
<   if (!isset($loadable_types)) {
<     $loadable_types = &drupal_static(__FUNCTION__);
<     if (!isset($loadable_types)) {
<       $loadable_types = db_query("SELECT DISTINCT entity_type FROM {pathauto_persist}")->fetchCol();
<     }
<   }
<   if (!in_array($type, $loadable_types)) {
<     return;
<   }
<
23,27c9
<     if (!isset($entities[$id]->path)) {
<       $entities[$id]->path = array();
<     }
<
<     if (is_array($entities[$id]->path) && !isset($entities[$id]->path['pathauto'])) {

---
>     if (!isset($entities[$id]->path) || (is_array($entities[$id]->path) && !isset($entities[$id]->path['pathauto']))) {
110d91
<   drupal_static_reset('pathauto_persist_entity_load');
```

### CODE REVIEW

**Comment by stooit** [comment]
I should also note the patch has been removed from the makefile as this is incorporated in the latest stable.

**Comment by seanhamlin** [comment]
PR looks good to me, if it passes, let it be merged.

**Comment by typhonius** [comment]
:fork_and_knife: PR passed. Merge away :balloon:

**Comment by fiasco** [comment]
a knife and fork? really?

**Pull request merged**
