### PR TITLE
Update views_bulk_operations to 7.x-3.5 (from 7.x-3.3)

### PR DESCRIPTION
**Pull request by deanvucic**
## https://www.drupal.org/project/views_bulk_operations/releases/7.x-3.5
Release notes
Changes since 7.x-3.4:

#2946220 by bkosborne: PHP 7.2+ future proofing, remove usage of deprecated "create_function()"
#2334625 by g.oechsler, larowlan: "Select all items on all pages" executed from last page affects only last page items
#2674166 by hbemtec, nagy.balint, joelpittet: "Select all" checkbox and sticky headers
#2475873 by attiks, joelpittet: Javascript blocks clicks on label elements
#2890878 by matthensley: Decrease js specificity for use with Bootstrap theme
#2800227 by joelpittet, cudevdev: 'Move to book' populates the menu_links table but not the book table.
#2718223 by joelpittet, Yuri: Fatal error: Call to undefined function EntityDefaultMetadataController::bundleOptionsList()
#2431131 by joelpittet, vijithaepa: Fatal error: Unsupported operand types in ...modules\views_bulk_operations\plugins\operation_types\action.class.php
#2873171 by joelpittet: PHP7 readiness
#2872389 by tmin: "Select All" option does not show up in some cases
#2867407 by hgoto: 2 patterns of jQuery selector are used for the same elements in views_bulk_operations.js
#2855939 by hgoto, stefanos.petrakis: Bulk operation buttons don't work after upgrade to 3.4 when Force Single selected
#2862687 by xdevx, joelpittet: Warning: call_user_func() expects parameter 1 to be a valid callback
#2855782 by stefanos.petrakis, hgoto, joelpittet, Liu Xin: Disable submit button works only after a second selection is done: Recent jQuery+WholeRowClickable
#2860320 by claudiu.cristea, joelpittet: Allow exceptions when toggling buttons
#2856575 by plach: "Select all on all pages" widget always displayed when the view has no pager
#2853029 by joelpittet, pjohn, tobiasb, nairb: views_bulk_operations_action_load_list not working
#2473889 by CvW: rules component with list as parameter creates a notice

## https://www.drupal.org/project/views_bulk_operations/releases/7.x-3.4

Release notes
Changes since 7.x-3.3:

#2505457 by dago.aceves, sambonner, joelpittet, joekers, k2abhishek, gbyte.co, CHENZEN002, klidifia, edward.radau: Cancel User Account: Delete account and make content belong to "Anonymous" issue
#2790293 by hgoto, aaronbauman, Plazik: Disable submit button until a selection is made
#2846885 by joelpittet, jerry: VBO operation fails via Drush, succeeds via UI
#2790293 by aaronbauman, hgoto, joelpittet: Disable submit button until a selection is made
#1871702 by axel.rutz, joelpittet, blackclover, bojanz, wizonesolutions: Load a list of entity from a VBO View doesn't work (AJAX error)
#1334088 by aaronbauman, rahul.shinde, emattias, askibinski, Ogredude, ikeigenwijs: Execute as User 1 - skip permission step
coding standard updates
#2305227 by lmeurs, sumthief, JordanMagnuson, gturnbull: Warning: mb_strlen() expects parameter 1 to be string, array given in drupal_strlen()
#2743999 by haggins, joelpittet, hobbsgoblin, Chris Burge: Archive files corrupted when they are in private file system
#2608360 by rafavermo, Reno Greenleaf, joelpittet, scott.whittaker: "Select all" checkbox works only once
#2820957: [warning] call_user_func() expects parameter 1 to be a valid callback, function 'views_bulk_operations_change_owner_action_info' not found or invalid function name views_bulk_operations.module:23
#2510934 by jeffschuler, junaidpv, heddn, ndobromirov: Add action to change entity author
#2508990 by snap_x, joelpittet: Incorrect displaying of a strong tag on the confirmation step on the bootstrap theme
#2474691 by Itangalo: Overwrites latest node revision
#2719059 by NitinSP, urvigala, wesruv, mayurjadhav: Remove !important from CSS
#1334374 by andrewbelcher, pfournier, rooby, David Hernández, akozma, mh86, f5.andrii, bojanz: Re-use generic entity views table
#2551301 by Lendude, drumm, Ashley George, sylus, daveferrara1, juanp.rey.z: Fix all VBO views on page using first VBO field settings
#2282079 by Steven Jones: No watchdog entry created on bulk node deletion
#2533740 by dewalt: VBO expired queues aren't cleaned by cron

### CODE REVIEW

**Comment by tobybellwood** [comment]
Test this

**Comment by tobybellwood** [comment]
Test this

**Comment by tobybellwood** [comment]
Test this

**Comment by tobybellwood** [comment]
Test this

**Comment by fubarhouse** [comment]
Superseded by #759

**Pull request closed without merging**
