### PR TITLE
Update webform to 7.x-4.16 (from 7.x-4.15)

### PR DESCRIPTION
**Pull request by deanvucic**
Of particular interest here is the "upload destination private files by default if available".

## https://www.drupal.org/project/webform

Changes since 7.x-4.15:

Coding standards
#2816303 by ilari.stenroth, Liam Morland, vinmassaro: Make file upload destination private files by default if available
#2901156 by dhruveshdtripathi, raynimmo: Fix undefined index: #id in theme_webform_element()
#2900109 by lambic: Undefined function webform_component_feature() when entitycache is enabled
#2713743 by joelstein: Add @placeholder support to Number component
#2604830 by heykarthikwithu, joelpittet: Code cleanup: Remove unused variables throughout the module
#2883514: Coding standards
#2873783: Disable form controls when hiding them
#2869746 by torotil: Return render arrays instead of strings
#2780283 by nightwalkr, Liam Morland: Fix undefined index in webform_component_include()
#2866630 by alexp999, Liam Morland: PHP Zip requirement should be Info, not Warning
#2683801 by nicrodgers, joel_osc: Translation of progress bar page breaks
#2857854 by pifagor, Liam Morland: Fix non-numeric value warning in PHP 7.1
#2860487 by mercepedraza: Set numeric values as "general" in Excel export
#2867012 by Munavijayalakshmi: Fix documentation spelling errors

### CODE REVIEW

**Comment by tobybellwood** [comment]
Test this

**Comment by tobybellwood** [comment]
Test this

**Review by pandaskii — APPROVED** [review]
Ready for testing

**Comment by tobybellwood** [comment]
Test should include (at a minimum) - inc conjunction with #632 :

Creation of private FS outside docroot
Configure Mailsystem to send emails
Configure Webform to attach files, and save them in private FS
Configure swiftmailer to use the private path for webform (most likely private://webform)
Configure webform clear to instantly clear
Ensure email arrives with attachment

**Comment by samhighley** [comment]
Hey @tobybellwood things have gone a bit south on the ANAO website today. First of all, all of our webforms that were embedded into nodes via preprocess disappeared and were replaced with the word 'array'. We appear to have resolved that issue using information here: 

https://www.drupal.org/node/2924380

The issue we have now is that file attachments to the aforementioned forms aren't coming through.

**Pull request merged**
