### PR TITLE
Drupal core 7.50 update

### PR DESCRIPTION
**Pull request by rooby**
For issue #295
- Update Drupal core to 7.50
- Remove patch for https://www.drupal.org/node/2678822

### CODE REVIEW

**Comment by fiasco** [comment]
test this

**Comment by seanhamlin** [comment]
Looking at the automated site install logs in Jenkins

```
The following module is missing from the file system: content. In        [error]
order to fix this, put the module back in its original location. For
more information, see the documentation page. in
_drupal_trigger_error_with_delayed_logging() (line 1128 of
/var/lib/jenkins/jobs/govcms_pull_request_builder/workspace/296-actual/docroot/includes/bootstrap.inc).
[63.22 sec, 96.96 MB]
```

Some quick googling found https://www.drupal.org/node/2487215 and also this blog post http://www.vdmi.nl/blog/i-went-drupal-733-and-all-i-got-was-slow-site

So it looks like either a contrib module or custom one is trying to load a file that does not exist.

I would recommend debug backtracing a local site install and seeing what module is causing this. This PR might be blocked until this is sorted.

**Comment by seanhamlin** [comment]
Also someone wrote this module which may help https://www.drupal.org/project/module_missing_message_fixer

**Comment by seanhamlin** [comment]
This is an example issue (module not in govCMS but it gives you an idea) https://www.drupal.org/node/2763555 to show you what the bug is.

**Comment by seanhamlin** [comment]
Using some grep foo, I think I have found it 

```
$ grep -nriI "module_load_include('inc', 'content'" *
profiles/govcms/modules/contrib/google_analytics_reports/google_analytics_reports.install:97:    module_load_include('inc', 'content', 'includes/module');
```

There is an issue for google_analytics_reports - https://www.drupal.org/node/2762675, and it seems that 7.x-3.1 includes this fix.

**Comment by seanhamlin** [comment]
The more I think about this PR, I think you should just push the update to google_analytics_reports in this PR, as we need to bump them in tandem.

**Comment by pandaskii** [comment]
Agree with @seanhamlin we have two options here:
1. A PR to bump google_analytics_reports, then rebase this PR
2. In this PR, include google_analytics_reports 3.1

More thoughts, should we remove dependencies[] = google_analytics_reports from govcms.info?

**Comment by seanhamlin** [comment]
My vote is for option #2, in a squashed single commit, with appropriate messaging to indicate why they are included together. This makes the most sense to me.

As for removing the google_analytics_reports from the default install, I am unsure on what the google_analytics_reports module even does, but that is certainly worth a follow up issue. I was under the impression that all agencies get their own analytics reports from GA directly (and not from within Drupal).

**Comment by aleayr** [comment]
Hi @rooby,

Would you be able to perform Option #2 above with this PR (including google_analytics_reports version 3.1)?

Then we can finalise testing and roll this in. Let me know if this presents an issue.

**Comment by fiasco** [comment]
test this

**Comment by aleayr** [comment]
Closed in favour of #368.

**Pull request closed without merging**
