### PR TITLE
Various Automated Testing Improvements

### PR DESCRIPTION
**Pull request by tobybellwood**
Using bex/behat-step-time-logger to report step times in Behat tests - to explain some of the variable timing we're seeing

### CODE REVIEW

**Comment by tobybellwood** [comment]
Test this

**Comment by tobybellwood** [comment]
Test this

**Comment by tobybellwood** [comment]
Test this

**Comment by tobybellwood** [comment]
Test this

**Comment by mgdhs** [comment]
Shouldn't it test itself? :P

**Comment by tobybellwood** [comment]
... @mgdhs it's more worrying that it can't even pass it's own tests!

**Comment by tobybellwood** [comment]
closing in favour of #750 - although some of the logic may apply!

**Pull request closed without merging**
