### PR TITLE
#199 - Added patches to the mac module to:

### PR DESCRIPTION
**Pull request by aleayr**
```
       - add security to the autocomplete callback
       - removed some unnecessary items from the info file
       - added a limit to the number of items displayed by the autocomplete to the install file.
```

### CODE REVIEW

**Comment by aleayr** [comment]
Hi @kurtsalsa, just taken this from your feature branch for testing to merge in, but getting conflict warnings. Are you able to check this out at all?

**Comment by kurtfoster** [comment]
@aleayr , I'm not sure when i'll get to it, I'm overbooked with govCMS work at the moment.

**Comment by aleayr** [comment]
@kurtsalsa No drama, @ruwanl was going to have a look into it as well.

**Comment by fiasco** [comment]
@srowlands (bot maintainer) said that the bot may not like the slash in the branch name. Use branch names with [a-zA-Z0-9] and it should work.

**Comment by Feng-Shui** [comment]
Was going to say it might be the hash in the branch name, bot didn't even appear to get the branch cloned.

**Comment by aleayr** [comment]
When I went to create the pull request, Github itself said the merge wouldn't work automatically, so I was expecting it to fail to be honest.

Might be a couple of issues then.

**Comment by pandaskii** [comment]
@aleayr we can close this one in favour of this pull request #276

**Comment by aleayr** [comment]
See #276.

**Pull request closed without merging**
